// This single-player adventure uses level milestones instead of trade/items.
export const EXTRA_SPECIES=[
['metapod','铁甲蛹','虫',11],['butterfree','巴大蝶','虫',12],['kakuna','铁壳蛹','虫',14],['beedrill','大针蜂','虫',15],['pidgeotto','比比鸟','飞行',17],['pidgeot','大比鸟','飞行',18],['raticate','拉达','一般',20],
['nidorina','尼多娜','毒',30],['nidoqueen','尼多后','毒',31],['nidorino','尼多力诺','毒',33],['nidoking','尼多王','毒',34],['clefable','皮可西','妖精',36],['ninetales','九尾','火',38],['golduck','哥达鸭','水',55],['arcanine','风速狗','火',59],['kadabra','勇基拉','超能',64],['alakazam','胡地','超能',65],['haunter','鬼斯通','幽灵',93],['gengar','耿鬼','幽灵',94],['steelix','大钢蛇','钢',208],['dragonair','哈克龙','龙',148],['dragonite','快龙','龙',149],
['pichu','皮丘','电',172],['cleffa','皮宝宝','妖精',173],['mareep','咩利羊','电',179],['flaaffy','茸茸羊','电',180],['wooper','乌波','水',194],['blissey','幸福蛋','一般',242],['happiny','小福蛋','一般',440],['munchlax','小卡比兽','一般',446],['scizor','巨钳螳螂','虫',212],['kleavor','劈斧螳螂','虫',900],
['espeon','太阳伊布','超能',196],['umbreon','月亮伊布','一般',197],['leafeon','叶伊布','草',470],['glaceon','冰伊布','冰',471],['sylveon','仙子伊布','妖精',700],['kirlia','奇鲁莉安','超能',281],['gardevoir','沙奈朵','超能',282],['gallade','艾路雷朵','格斗',475],['lairon','可多拉','钢',305],['altaria','七夕青鸟','龙',334],['lampent','灯火幽灵','幽灵',608],['gurdurr','铁骨土人','格斗',533],['conkeldurr','修建老匠','格斗',534],['floatzel','浮潜鼬','水',419],['herdier','哈约克','一般',507],['stoutland','长毛狗','一般',508],['cinccino','奇诺栗鼠','一般',573]
];
export const LEVEL_EVOLUTIONS={bulbasaur:['ivysaur',12],ivysaur:['venusaur',22],charmander:['charmeleon',12],charmeleon:['charizard',22],squirtle:['wartortle',12],wartortle:['blastoise',22],magikarp:['gyarados',15],caterpie:['metapod',7],metapod:['butterfree',10],weedle:['kakuna',7],kakuna:['beedrill',10],pidgey:['pidgeotto',18],pidgeotto:['pidgeot',36],rattata:['raticate',20],nidoran_f:['nidorina',16],nidoran_m:['nidorino',16],psyduck:['golduck',33],abra:['kadabra',16],gastly:['haunter',25],dratini:['dragonair',30],dragonair:['dragonite',55],mareep:['flaaffy',15],flaaffy:['ampharos',30],wooper:['quagsire',20],ralts:['kirlia',20],aron:['lairon',32],lairon:['aggron',42],swablu:['altaria',35],litwick:['lampent',41],timburr:['gurdurr',25],buizel:['floatzel',26],lillipup:['herdier',16],herdier:['stoutland',32]};
export const CHOICE_EVOLUTIONS={pichu:[15,'pikachu'],cleffa:[15,'clefairy'],happiny:[15,'chansey'],munchlax:[20,'snorlax'],pikachu:[25,'raichu'],nidorina:[25,'nidoqueen'],nidorino:[25,'nidoking'],clefairy:[25,'clefable'],vulpix:[25,'ninetales'],growlithe:[25,'arcanine'],kadabra:[36,'alakazam'],haunter:[36,'gengar'],onix:[30,'steelix'],chansey:[30,'blissey'],scyther:[30,'scizor','kleavor'],eevee:[20,'vaporeon','jolteon','flareon','espeon','umbreon','leafeon','glaceon','sylveon'],kirlia:[30,'gardevoir','gallade'],lampent:[45,'chandelure'],gurdurr:[40,'conkeldurr'],minccino:[25,'cinccino']};
export const experienceNeeded=m=>m.level>=100?0:m.level*14;
export function gainExperience(m,amount){const changes=[];if(m.level<100)m.xp+=amount;while(m.level<100&&m.xp>=experienceNeeded(m)){m.xp-=experienceNeeded(m);m.level++;m.max=30+m.level*5;m.hp=Math.min(m.max,m.hp+10)}if(m.level===100)m.xp=0;let ev;while((ev=LEVEL_EVOLUTIONS[m.id])&&m.level>=ev[1]){changes.push([m.id,ev[0]]);m.id=ev[0]}return changes;}
