import {CHOICE_EVOLUTIONS,LEVEL_EVOLUTIONS,experienceNeeded,gainExperience} from './evolution.js';
import {WILDLANDS,wildlandIndex,addWildlandGates} from './wildlands.js'; import {freshLegend,migrateLegend,LEGENDS} from './legend-data.js'; import {ensureLegends,dismissLegend} from './legend-world.js'; import {research,legendInteraction} from './legend-story.js'; import {legendBattleFX} from './legend-fx.js'; import {RELAY_CHAPTERS,STORY_DIRECTIONS} from './relay-story.js';
import {DIRS,OPPOSITE,townEndpoint,placeAtEntrance,TOWN_GRID,CONNECTIONS} from './geography.js';
import {ROUTES,routeIndex} from './side-routes.js';
import {LANDMARKS,MEMORIES,landmarkFor} from './story.js'; import {battleFX} from './battle-fx.js'; import {DEX,MON,AREAS,QUESTS,MOVES,EVOLVE,effectiveness} from './data.js';
import {World} from './world.js?v=regions-17-solid-buildings';
import {freshEcho,migrateEcho,CHARACTERS,OBSERVATIONS,EVIDENCE,CASES,BEHAVIORS,ENDINGS,endingFor,echoObjective,TRAIT_NAMES} from './echo-data.js';
import {COLLECTION_TRACKS,COLLECTION_AUDIO,SCENE_AUDIO,ROUTE_MUSIC} from './music-library.js';
import {prepareSources,sourceUrl} from './source-sprites.js';
const $=s=>document.querySelector(s),KEY='pokemon-echoes-v1',SLOT_KEY='pokemon-echoes-save-slots-v1',SLOT_PREFIX='pokemon-echoes-save-slot-v1-',SLOT_COUNT=9;
const STARTERS=['bulbasaur','charmander','squirtle'];
const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const makeMon=(id,level=6)=>({id,level,hp:30+level*5,max:30+level*5,bond:10,xp:0});
function experienceBar(m){const need=experienceNeeded(m),value=need?Math.min(need,m.xp):0;return `<div class="xp-meter"><small>EXP ${need?`${value} / ${need}`:'已满级'}</small><div class="xp-bar" role="progressbar" aria-label="升级经验" aria-valuemin="0" aria-valuemax="${need||1}" aria-valuenow="${need?value:1}"><i style="width:${need?value/need*100:100}%"></i></div></div>`}
function evolutionActions(m,i){const rule=CHOICE_EVOLUTIONS[m.id],normal=LEVEL_EVOLUTIONS[m.id];if(!rule)return normal?`<small class="evolution-note">Lv.${normal[1]} → ${MON[normal[0]].name}</small>`:'';return `<small class="evolution-note">本作单机适配：Lv.${rule[0]} 后选择进化，无需通信或道具。</small>${rule.slice(1).map(id=>`<button data-evolve="${i}:${id}" ${m.level<rule[0]?'disabled':''}>进化为${MON[id].name}</button>`).join('')}`}
function bindEvolution(){document.querySelectorAll('[data-evolve]').forEach(b=>b.onclick=()=>{const [i,id]=b.dataset.evolve.split(':'),m=state.team[+i],rule=CHOICE_EVOLUTIONS[m.id];if(!rule||m.level<rule[0]||!rule.slice(1).includes(id))return;dialog('确认进化',`${MON[m.id].name}将进化为${MON[id].name}，等级与经验保留。进化后不能退回原形态。`,[{text:'确认进化',fn:()=>{m.id=id;seen(id);if(!state.caught.includes(id))state.caught.push(id);save();sync();team()}},{text:'暂不进化',fn:team}],m.id+'-front')})}
const fresh=()=>({version:1,area:0,stage:0,team:[makeMon('pikachu',8)],box:[],seen:['pikachu'],caught:['pikachu'],money:1200,balls:15,potions:5,berries:8,coins:100,badges:0,fished:0,safari:0,battles:0,petWins:0,steps:0,starter:false,masterBalls:0,legend:freshLegend(),discoveries:[],events:[],legendaries:[],responses:{},surveys:[],relayReported:false,echo:freshEcho()});
function validate(raw){if(!raw||raw.version!==1||!Array.isArray(raw.team)||!raw.team.length||raw.team.length>6)throw Error('存档格式不正确');const s=fresh();for(const k of ['area','stage','money','balls','potions','berries','coins','badges','fished','safari','battles','petWins','steps']){if(!Number.isFinite(raw[k])||raw[k]<0)throw Error('存档数据损坏');s[k]=Math.floor(raw[k])}if(s.stage>6||s.area>5)throw Error('存档进度不正确');for(const k of ['team','box']){if(!Array.isArray(raw[k])||raw[k].length>1000)throw Error('队伍数据不正确');s[k]=raw[k].map(m=>{if(!MON[m.id]||!Number.isInteger(m.level)||m.level<1||m.level>100)throw Error('宝可梦数据不正确');const t=makeMon(m.id,m.level);t.hp=Math.max(0,Math.min(t.max,Number(m.hp)||0));t.bond=Math.max(0,Math.min(100,Number(m.bond)||0));t.xp=t.level===100?0:Math.max(0,Math.min(t.level*14-1,Number.isFinite(m.xp)?m.xp:0));return t})}for(const k of ['seen','caught'])s[k]=[...new Set((raw[k]||[]).filter(id=>MON[id]))];s.discoveries=[...new Set((Array.isArray(raw.discoveries)?raw.discoveries:[]).filter(x=>Number.isInteger(x)&&x>=0&&x<6))];s.events=[...new Set((Array.isArray(raw.events)?raw.events:[]).filter(x=>typeof x==='string'&&/^[0-5]:(rescue|memory|spring)$/.test(x)))];s.legendaries=[...new Set((Array.isArray(raw.legendaries)?raw.legendaries:[]).filter(x=>['articuno','zapdos','moltres'].includes(x)))];s.responses={};for(let i=0;i<6;i++)if(['listen','promise'].includes(raw.responses?.[i]))s.responses[i]=raw.responses[i];s.surveys=[...new Set((Array.isArray(raw.surveys)?raw.surveys:[]).filter(x=>typeof x==='string'&&/^[0-5]:[0-2]$/.test(x)))];s.relayReported=!!raw.relayReported;s.starter=!!raw.starter;s.masterBalls=Number.isInteger(raw.masterBalls)&&raw.masterBalls>=0?Math.min(raw.masterBalls,1000000):0;s.legend=migrateLegend(raw.legend);s.echo=migrateEcho(raw.echo,s.stage);if(raw.room&&['home','heal','shop','lab','berry','ranger','pet','arcade','cave','grotto','echo-district',...ROUTES.map((_,i)=>'route-'+i),...WILDLANDS.map((_,i)=>'wildland-'+i)].includes(raw.room.service)&&typeof raw.room.name==='string'&&raw.room.name.length<80&&raw.room.returnPoint?.area===s.area&&Number.isFinite(raw.room.returnPoint.x)&&Number.isFinite(raw.room.returnPoint.z)&&Math.abs(raw.room.returnPoint.x)<21&&Math.abs(raw.room.returnPoint.z)<21)s.room={name:raw.room.name,service:raw.room.service,returnPoint:{...raw.room.returnPoint}};if(s.room&&raw.room.districtReturn){const d=raw.room.districtReturn;if(d.area===s.area&&d.room?.service==='echo-district'&&typeof d.room.name==='string'&&d.room.name.length<80&&d.point?.area===s.area&&[d.x,d.z,d.point.x,d.point.z].every(Number.isFinite)&&Math.abs(d.x)<9&&Math.abs(d.z)<8&&Math.abs(d.point.x)<21&&Math.abs(d.point.z)<21)s.room.districtReturn={area:d.area,room:{name:d.room.name,service:'echo-district'},point:{...d.point},x:d.x,z:d.z};}return s;}
const slotKey=index=>SLOT_PREFIX+index;
const blankSlotRegistry=()=>({version:1,active:0,slots:Array(SLOT_COUNT).fill(null)});
function readSlotRegistry(){try{const registry=JSON.parse(localStorage.getItem(SLOT_KEY));if(registry?.version===1&&Array.isArray(registry.slots)&&registry.slots.length===SLOT_COUNT&&Number.isInteger(registry.active)&&registry.active>=0&&registry.active<SLOT_COUNT)return registry}catch{}return null}
function slotSummary(save,updatedAt=Date.now()){return {updatedAt,area:save.area,stage:save.stage,leader:save.team[0]?.id||'pikachu',level:save.team[0]?.level||1,caught:save.caught.length}}
let slotRegistry=readSlotRegistry(),activeSlot=0,loadError=false;
if(!slotRegistry){
 slotRegistry=blankSlotRegistry();
 try{
  for(let i=0;i<SLOT_COUNT;i++){const raw=localStorage.getItem(slotKey(i));if(raw){try{slotRegistry.slots[i]=slotSummary(validate(JSON.parse(raw)))}catch{slotRegistry.slots[i]={damaged:true}}}}
  const legacy=localStorage.getItem(KEY);
  if(legacy&&!localStorage.getItem(slotKey(0))){const migrated=validate(JSON.parse(legacy));localStorage.setItem(slotKey(0),JSON.stringify(migrated));slotRegistry.slots[0]=slotSummary(migrated)}
  localStorage.setItem(SLOT_KEY,JSON.stringify(slotRegistry))
 }catch{loadError=true}
}
activeSlot=slotRegistry.active;let state=fresh();try{const d=localStorage.getItem(slotKey(activeSlot))||(activeSlot===0?localStorage.getItem(KEY):null);if(d)state=validate(JSON.parse(d))}catch{loadError=true};state.echo??=migrateEcho(null,state.stage)
// Repair an older impossible save state where the flag was written before the
// selected Pokemon reached the party or storage box.
if(state.stage===0&&state.starter&&!STARTERS.some(id=>[...state.team,...state.box].some(m=>m.id===id)))state.starter=false;
let world,battle=null,busy=false,mini=null,modalCleanup=null,previousFocus=null,music=false,audioCtx=null,audioTimer=null,audioGain=null,musicStep=0,currentTrack=null,bgmAudio=null,bgmTrack=null,victoryAudio=null,musicJingle=false,jingleTimer=null,toastTimer=null;
const MUSIC_KEY='pokemon-echoes-music';
let musicChoice='auto',lastMusicScene=null;
const MUSIC=[
 {id:'auto',name:'随场景自动切换'},
 {id:'town',name:'青岚镇 · 冒险开始',bpm:126,root:0,wave:'square',melody:[0,4,7,9,7,4,2,4,5,9,12,9,7,4,2,0],bass:[0,0,5,5,7,7,4,4],accent:0},
 {id:'forest',name:'微光森林 · 常青森林',bpm:116,root:-2,wave:'triangle',melody:[0,3,5,7,10,7,5,3,0,2,3,7,5,3,2,0],bass:[0,0,-5,-5,3,3,-2,-2],accent:1},
 {id:'coast',name:'潮汐渔港 · 凯那市',bpm:108,root:5,wave:'sine',melody:[0,2,4,7,9,7,4,2,0,-3,0,4,7,4,2,0],bass:[0,-5,0,-5,5,0,4,-1],accent:2},
 {id:'safari',name:'翠野保育区 · 白色森林',bpm:120,root:-5,wave:'triangle',melody:[0,5,7,10,7,5,3,5,0,3,5,8,10,8,5,3],bass:[0,0,3,3,5,5,-2,-2],accent:1},
 {id:'arcade',name:'星灯街 · 玉虹市',bpm:148,root:2,wave:'square',melody:[0,7,12,7,3,10,12,10,5,12,14,12,7,14,15,14],bass:[0,0,7,7,5,5,3,3],accent:3},
 {id:'center',name:'宝可梦中心 · 恢复',bpm:96,root:0,wave:'sine',melody:[0,4,7,12,11,7,4,2,0,2,4,7,9,7,4,0],bass:[0,0,5,5,4,4,0,0],accent:4},
 {id:'shop',name:'商店与补给 · 柜台',bpm:132,root:0,wave:'square',melody:[0,2,4,5,7,5,4,2,0,4,7,9,7,5,4,2],bass:[0,0,5,5,7,7,0,0],accent:0},
 {id:'lab',name:'大木研究所 · 发明',bpm:112,root:-1,wave:'triangle',melody:[0,4,8,7,4,1,4,7,8,11,8,7,4,1,0,-2],bass:[0,-5,0,-5,4,-1,4,-1],accent:2},
 {id:'home',name:'家与伙伴俱乐部 · 小憩',bpm:88,root:0,wave:'sine',melody:[0,4,7,9,7,4,2,0,-3,0,2,4,7,4,2,0],bass:[0,0,5,5,0,0,4,4],accent:4},
 {id:'ruin',name:'回响遗迹 · 紫苑镇',bpm:104,root:-7,wave:'triangle',melody:[0,7,10,12,15,12,10,7,5,10,12,17,15,12,10,7],bass:[0,0,-5,-5,-2,-2,-7,-7],accent:5},
 {id:'battle',name:'野外对战 · 训练家心跳',bpm:156,root:-2,wave:'sawtooth',melody:[0,0,7,0,10,7,12,10,0,3,7,10,12,15,12,7],bass:[0,0,0,7,0,0,0,5],accent:3},
 {id:'final',name:'最终试炼 · 回响之心',bpm:138,root:-5,wave:'sawtooth',melody:[0,7,12,15,14,12,10,7,5,10,14,17,15,14,12,10],bass:[0,0,-5,-5,3,3,-2,-2],accent:5}
];
MUSIC.splice(1,0,...COLLECTION_TRACKS);
const TRACKS=Object.fromEntries(MUSIC.filter(t=>t.id!=='auto').map(t=>[t.id,t]));
const LICENSED_AUDIO={town:'assets/music/pallet-town.mp3',forest:'assets/music/route.mp3',coast:'assets/music/coast.mp3',safari:'assets/music/route.mp3',arcade:'assets/music/jigglypuff-song.mp3',center:'assets/music/pokemon-center.mp3',shop:'assets/music/pewter-city.mp3',lab:'assets/music/oak-lab.mp3',home:'assets/music/home.mp3',ruin:'assets/music/birch-lab.mp3',battle:'assets/music/wild-battle.mp3',final:'assets/music/wild-battle.mp3'};
Object.assign(LICENSED_AUDIO,COLLECTION_AUDIO,SCENE_AUDIO);
const VICTORY_AUDIO='assets/music/wild-victory.mp3';
const BADGE_AUDIO='assets/music/badge-fanfare.mp3';
const img=(id,side='front',cls='')=>`<img class="${cls}" src="${sourceUrl(id+'-'+side)}" alt="${MON[id]?.name||id}">`;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200)}
// Commit the slot and its index before switching the live journey.
function persistSlot(index,next){
 let previous;
 try{
  previous=localStorage.getItem(slotKey(index));
  const registry={...slotRegistry,active:index,slots:[...slotRegistry.slots]};
  registry.slots[index]=slotSummary(next);
  localStorage.setItem(slotKey(index),JSON.stringify(next));
  try{localStorage.setItem(SLOT_KEY,JSON.stringify(registry))}
  catch(error){if(previous===null)localStorage.removeItem(slotKey(index));else localStorage.setItem(slotKey(index),previous);throw error}
  slotRegistry=registry;
  // Compatibility copy is not authoritative once the nine-slot index exists.
  try{localStorage.setItem(KEY,JSON.stringify(next))}catch{}
  return true;
 }catch{toast('保存失败，未切换旅程。请在背包导出存档备份。');return false}
}
function save(manual=false){
 if(loadError){if(manual)toast('原存档无法读取，已保护原始数据，暂不覆盖。');return false}
 state.echo??=freshEcho();
 state.room=world?.interior?{...world.interior,returnPoint:world.returnPoint,districtReturn:world.districtReturn||null}:null;
 if(!persistSlot(activeSlot,state))return false;
 if(manual)toast(`旅程已保存到 ${activeSlot+1} 号存档栏。`);
 return true;
}
function readSlot(index){try{const raw=localStorage.getItem(slotKey(index));return raw?validate(JSON.parse(raw)):null}catch{return null}}
function occupiedSlot(index){try{return localStorage.getItem(slotKey(index))!==null}catch{return true}}
function slotTiles(mode){return Array.from({length:SLOT_COUNT},(_,index)=>{
 const saved=readSlot(index),occupied=occupiedSlot(index),active=index===activeSlot,meta=slotRegistry.slots[index];
 return `<article class="slot-tile ${active?'active':''}"><span>存档 ${String(index+1).padStart(2,'0')}</span><b>${saved?`Lv.${saved.team[0].level} ${MON[saved.team[0].id].name}`:occupied?'存档暂不可读取':'空白旅程'}</b><small>${saved?`${AREAS[saved.area].name} · 图鉴 ${saved.caught.length} · 章节 ${saved.stage===6?'完成':saved.stage+1}`:occupied?'原始数据已保留':'可开始一段新的旅程'}</small>${saved&&meta?.updatedAt?`<small>${new Date(meta.updatedAt).toLocaleString('zh-CN')}</small>`:''}${active?'<em>当前使用</em>':''}<div>${mode==='save'?`<button class="button secondary" data-slot-save="${index}">${active?'保存当前栏':'保存到这里'}</button>${saved&&!active?`<button class="slot-load" data-slot-load="${index}">读取</button>`:''}`:`<button class="button" data-slot-new="${index}" ${occupied?'disabled':''}>${occupied?'已有旅程':'在此开始'}</button>`}</div></article>`
 }).join('')}
function selectSaveSlot(){
 if(battle){toast('请先结束当前对战，再管理存档。');return}
 if(!save())return;
 modal('保存旅程 · 九个存档栏',`<p class="muted">当前进度已保留在 ${activeSlot+1} 号栏。保存到另一栏会复制当前旅程，并切换为该栏的自动保存目标；也可以读取其他旅程。</p><div class="slot-grid">${slotTiles('save')}</div>`,'SAVE SLOTS');
 document.querySelectorAll('[data-slot-save]').forEach(button=>button.onclick=()=>{
  const target=+button.dataset.slotSave;
  const complete=()=>{if(!persistSlot(target,state))return;activeSlot=target;closeModal();toast(`旅程已保存到 ${target+1} 号存档栏。`)};
  if(target!==activeSlot&&occupiedSlot(target))confirmSlotOverwrite(target,'保存当前旅程',complete);else complete()
 });
 document.querySelectorAll('[data-slot-load]').forEach(button=>button.onclick=()=>loadSlot(+button.dataset.slotLoad))
}
function confirmSlotOverwrite(index,action,complete){modal(`${action}到 ${index+1} 号栏`, `<p>该存档栏已有旅程。只有 ${index+1} 号栏会被替换；当前 ${activeSlot+1} 号栏保持不变。</p><div class="actions"><button class="button" id="confirm-slot-overwrite">确认替换</button><button class="button secondary" id="cancel-slot-overwrite">返回</button></div>`,'CONFIRM SAVE SLOT');$('#confirm-slot-overwrite').onclick=complete;$('#cancel-slot-overwrite').onclick=selectSaveSlot}
function loadSlot(index){
 if(battle)return;
 const next=readSlot(index);if(!next){toast('这个存档栏无法读取。');return}
 if(!save()||!persistSlot(index,next))return;
 activeSlot=index;state=next;closeModal();restoreScene();sync();toast(`已读取 ${index+1} 号存档栏。`)
}
function newGame(){
 if(battle){toast('请先结束当前对战，再开始新旅程。');return}
 if(!save())return;
 modal('开始新游戏 · 选择空白栏',`<p class="muted">当前 ${activeSlot+1} 号栏已保存。新游戏只使用空白栏，已有旅程全部保留。${Array.from({length:SLOT_COUNT},(_,i)=>occupiedSlot(i)).every(Boolean)?'九个栏位已满，请读取已有旅程继续游玩。':''}</p><div class="slot-grid">${slotTiles('new')}</div>`,'NEW ADVENTURE');
 document.querySelectorAll('[data-slot-new]').forEach(button=>button.onclick=()=>{
  const target=+button.dataset.slotNew;if(occupiedSlot(target))return;
  const next=fresh();if(!persistSlot(target,next))return;
  activeSlot=target;state=next;loadError=false;closeModal();restoreScene();sync();
  toast(`新的旅程已建立在 ${target+1} 号存档栏。去见见大木博士吧。`)
 })
}
function seen(id){if(!state.seen.includes(id))state.seen.push(id)}
function catchMon(id,level){seen(id);if(!state.caught.includes(id))state.caught.push(id);const mon=makeMon(id,level);if(state.team.length<6)state.team.push(mon);else state.box.push(mon);save();sync();return state.team.includes(mon)?'加入了队伍':'送到了后备盒'}
function shardCount(){return state.stage<2?0:Math.min(3,state.stage-1)}
function legendAPI(){return {state,world,dialog,save,sync,closeModal,startBattle}} function sync(){if(world)world.echoState=state.echo;if(world&&world.storyStage!==state.stage){world.storyStage=state.stage;if(!world.interior){const pos=world.pos.clone();world.load(state.area);world.pos.copy(pos);world.fpos.copy(pos);world.trail=[pos.clone()]}}if(world){addWildlandGates(world);ensureLegends(world,state);}const base=AREAS[state.area],room=world?.interior,a=room?{...base,name:room.name,sub:base.name+(room.service==='echo-district'?' · 故事街区':routeIndex(room)>=0||wildlandIndex(room)>=0?' · 户外支路':' · 室内'),en:(room.service==='echo-district'?'DISTRICT / ':routeIndex(room)>=0||wildlandIndex(room)>=0?'TRAIL / ':'INDOOR / ')+base.en,hint:world.roomNote}:base,q=QUESTS[state.stage];$('#location').textContent=a.name;$('#location-sub').textContent=a.sub;$('#area-name').textContent=a.name;$('#area-en').textContent=a.en;$('#area-no').textContent=String(state.area+1).padStart(2,'0');$('#scene-note').textContent=a.hint;$('#quest-title').textContent=q.title;$('#quest-text').textContent=q.text+' '+STORY_DIRECTIONS[state.stage];$('#quest-goal').textContent=q.goal;if(state.stage===6){$('#quest-title').textContent='远方的回应';$('#quest-text').textContent=state.legend.accepted?'记录三处指定区域的生态样点，提交后获得大师球。打开旅程手记查看本轮地点与神兽线索。':'回到大木研究所，调查主线之后出现的新异象。';$('#quest-goal').textContent='与博士交谈 / 领取调查奖励';}$('#chapter').textContent=state.stage===6?'终章 / 完成':`章节 / ${String(state.stage+1).padStart(2,'0')}`;$('#story-progress').style.width=state.stage/6*100+'%';$('#story-count').textContent=`回响碎片 ${shardCount()} / 3`;$('#party-count').textContent=String(state.team.length).padStart(2,'0')+' / 06';$('#party-list').innerHTML=state.team.slice(0,3).map(m=>`<div class="party-row">${img(m.id)}<div class="party-info"><strong>${MON[m.id].name}</strong><small>Lv. ${m.level}</small><div class="hp-bar"><i style="width:${m.hp/m.max*100}%"></i></div><em>${m.hp} / ${m.max} HP</em>${experienceBar(m)}</div></div>`).join('');$('#money').textContent='₽ '+state.money.toLocaleString();$('#trainer-stats').textContent=`图鉴 ${state.caught.length} · 徽章 ${state.badges}`;$('#follow-name').textContent=MON[state.team[0].id].name;if(world)world.setFollower(state.team[0].id);updateMusic();}
function modal(title,body,kicker='YOUR ADVENTURE'){if(modalCleanup){modalCleanup();modalCleanup=null}if($('#modal').hidden)previousFocus=document.activeElement;$('#modal-title').textContent=title;$('#modal-kicker').textContent=kicker;$('#modal-body').innerHTML=body;$('#modal').hidden=false;world.paused=true;world.keys.clear();world.target=null;$('#close').focus()}
function closeModal(){if(modalCleanup){modalCleanup();modalCleanup=null}$('#modal').hidden=true;mini=null;world.paused=!!battle;(previousFocus?.isConnected?previousFocus:$('#world')).focus()}
function dialog(speaker,text,buttons=[{text:'继续探索',fn:closeModal}],portrait='professor'){modal(speaker,`<img class="dialog-portrait" src="${sourceUrl(portrait)}" alt="${speaker}"><p class="dialog-text">${text}</p><div style="clear:both"></div><div class="actions">${buttons.map((b,i)=>`<button class="button ${i?'secondary':''}" data-dialog="${i}">${b.text}</button>`).join('')}</div>`,'A MOMENT IN YOUR JOURNEY');buttons.forEach((b,i)=>$(`[data-dialog="${i}"]`).onclick=b.fn)}
function advance(stage){if(state.stage!==stage)return;state.stage++;state.money+=300;save();sync();if(stage===1||stage===5)playBadgeMusic();tone(660,.13);setTimeout(()=>tone(880,.18),160)}
function chooseStarter(id){
 if(state.stage!==0){closeModal();toast('你已经领取过最初的伙伴了。');return}
 if(!STARTERS.includes(id)){toast('这只宝可梦暂时不能作为最初的伙伴。');return}
 const existing=STARTERS.find(starterId=>[...state.team,...state.box].some(m=>m.id===starterId));
 if(existing){
  state.starter=true;advance(0);closeModal();toast(`${MON[existing].name}已经在队伍中，旅程可以继续了。`);return
 }
 state.starter=true;
 seen(id);if(!state.caught.includes(id))state.caught.push(id);
 const mon=makeMon(id,8);if(state.team.length<6)state.team.push(mon);else state.box.push(mon);
 advance(0);closeModal();toast(`${MON[id].name}加入了队伍！按 M 打开地图，前往微光森林。`)
}
function starterSelection(){
 modal('每一段羁绊，都有一个开始',`<p>皮卡丘会继续陪着你。再邀请一位伙伴加入队伍吧。</p><div class="team-grid">${STARTERS.map(id=>`<div class="team-tile">${img(id)}<h3>${MON[id].name}</h3><span class="type">${MON[id].type}</span><br><button class="button" data-starter="${id}">选择${MON[id].name}</button></div>`).join('')}</div>`,'YOUR FIRST COMPANION');
 document.querySelectorAll('[data-starter]').forEach(b=>b.onclick=()=>chooseStarter(b.dataset.starter));
}
function sideEvent(id){const kind={'lost-pokemon':'rescue','dream-memory':'memory','hidden-spring':'spring'}[id],key=state.area+':'+kind;if(state.events.includes(key)){dialog('旧日的回响','伙伴还记得你们在这里度过的时刻。这处奇遇已经完成，其他地区也许还有新的线索。',undefined,state.team[0].id+'-front');return}const complete=()=>{if(state.events.includes(key))return;state.events.push(key);state.team[0].bond=Math.min(100,state.team[0].bond+8);state.potions+=2;let text='伙伴羁绊 +8，获得伤药 ×2。';if(kind==='spring'){state.team.forEach(m=>m.hp=m.max);text='清凉的泉水恢复了全队体力。'+text}if(kind==='memory'){const count=state.events.filter(x=>x.endsWith(':memory')).length;text=`已收集梦境记忆 ${count} / 6。`+text;if(count===3){const where=catchMon('abra',12);text+=' 梦中的凯西回应了你，'+where+'！'}if(count===6){const where=catchMon('clefairy',16);text+=' 六段记忆拼成完整星图，皮皮'+where+'！'}}save();sync();dialog('这段相遇，留在了旅程里',text,undefined,state.team[0].id+'-front')};if(kind==='rescue')dialog('石缝里传来小小的歌声','一只皮皮迷失在回声中。它不需要一场战斗，只需要有人陪它安静下来。',[{text:'让伙伴陪它慢慢唱完',fn:complete},{text:'记住这里，稍后回来',fn:closeModal}],'clefairy-front');else if(kind==='memory'){const stories=['风铃响起时，离家的人曾许愿：下一次回家，要带伙伴看看世界。','森林没有吞没那条路，只是等一个愿意听见虫鸣的人。','潮水一次次退去，仍替远航的人守着归来的岸。','最强大的训练家也曾放下精灵球，等一只害怕的宝可梦主动靠近。','城市熄灯之后，仍有人为迷路的伙伴留了一扇亮着的窗。','石壁上的影子从来不是敌人，而是我们曾经害怕迈出的下一步。'];dialog('梦之石 · 遗失的愿望',MEMORIES[state.area]+'<br>梦之石保存着七年前的救援记忆。你与伙伴静静听完。',[{text:'与伙伴一同记住这段梦',fn:complete},{text:'暂时离开',fn:closeModal}],'abra-front')}else dialog('花谷的秘密','拉普拉斯轻轻哼唱。你可以在泉边休息，让伙伴重新振作。',[{text:'一起在泉边休息',fn:complete},{text:'先在花谷走走',fn:closeModal}],'lapras-front')}
function legendaryQuest(){const quests={1:{id:'articuno',kind:'memory',task:'记录三处不同地区的梦之石',title:'冰之誓约 · 记忆不会消融'},2:{id:'zapdos',kind:'rescue',task:'帮助三处不同地区迷路的皮皮',title:'雷之誓约 · 回应微弱的呼唤'},5:{id:'moltres',kind:'spring',task:'在三处不同地区的隐秘泉水休息',title:'火之誓约 · 把温暖带回旅途'}};const q=quests[state.area];if(!q)return;if(state.legendaries.includes(q.id)){dialog(q.title,'誓约石已经留下你的名字。这位伙伴已加入队伍或后备盒，无法重复领取。',undefined,q.id+'-front');return}const count=state.events.filter(x=>x.endsWith(':'+q.kind)).length;dialog(q.title,`${q.task}：${Math.min(count,3)} / 3。<br>${count>=3?'你的行动唤醒了守护者！誓约石会先恢复全队体力，随后开始试炼。获胜即可获得这位伙伴，失败可以回来重试。':'守护者尚未苏醒。探索各地石窟与花谷，完成誓约后再回来。'}`,count>=3?[{text:'接受神兽试炼',fn:()=>{closeModal();heal();startBattle(q.id,18,'legendary:'+q.id)}},{text:'稍后挑战',fn:closeModal}]:[{text:'继续寻找线索',fn:closeModal}],q.id+'-front')}
function storyPlace(){const p=landmarkFor(state.area,state.stage),ready=state.stage>=[6,2,3,4,5,6][state.area],reply=state.responses[state.area];let text=ready?p.late:p.early;if(reply&&!p.absent)text+=reply==='listen'?'<br><br>“你上次没有急着接话，我记得。”对方朝你的伙伴笑了笑。':'<br><br>“你说过还会回来。”对方把长凳上的落叶拂去，给你们留了位置。';if(state.stage===6)text+='<br><br>远处有风铃响了三声。你们等了一会儿，一起给出回答。';const answer=choice=>{const first=!state.responses[state.area];state.responses[state.area]=choice;if(first)state.team[0].bond=Math.min(100,state.team[0].bond+3);save();sync();dialog(p.speaker,choice==='listen'?'你没有打断。伙伴在你身旁坐下，直到对方把没说完的话讲完。<br>这次相处已记入旅程手记。':'“下次经过，我们还会来看你。”伙伴轻轻碰了碰你的手。<br>这句约定已记入旅程手记。',undefined,p.sprite)};if(p.absent){dialog(p.speaker,text,undefined,p.sprite);return}dialog(p.speaker+' · '+p.name,text,[{text:'坐下来，听对方说完',fn:()=>answer('listen')},{text:'约好下次再见',fn:()=>answer('promise')},{text:'继续旅程',fn:closeModal}],p.sprite)}
function heal(){if(world)world.healUntil=world.time+2.5;state.team.forEach(m=>m.hp=m.max);save();sync();tone(660,.2)}
function travel(index,fromRoute=null){if(battle)return;if(index===5&&state.stage<5){toast('收集三枚碎片并完成伙伴节奏挑战后，遗迹就会开放。');return}closeModal();world.districtReturn=null;state.area=index;world.storyStage=state.stage;world.load(index);if(typeof fromRoute==='number')placeAtEntrance(world,townEndpoint(fromRoute,index));else if(typeof fromRoute==='string')placeAtEntrance(world,DIRS[fromRoute]);sync();save();toast(`抵达 ${AREAS[index].name}`)}
function interact(){if(battle||!$('#modal').hidden)return;const e=world.nearest();if(!e){toast('靠近人物、建筑或野生宝可梦，再按 E 互动。');return}if(e.wildlandTown!==undefined){const gate=e.wildlandGate;travel(e.wildlandTown);if(!world.interior){const g=world.entities.find(v=>v.id==='wildland-gate-'+gate);if(g){world.pos.set(g.x,0,g.z);world.fpos.copy(world.pos);world.trail=[world.pos.clone()];save()}}return}if(legendInteraction(e,legendAPI()))return;if(echoInteract(e))return;if(e.portal){world.enter(e);sync();save();toast('进入 '+e.name+' · 沿路牌返回');return}switch(e.id){
case 'prof':case 'lab':if(state.stage===6&&state.surveys.length===18){relayReport();break}if(state.stage===0){dialog('大木博士',QUESTS[0].dialog,[{text:'选择一位新的同行伙伴',fn:starterSelection}]);}else dialog('大木博士',state.stage===6?QUESTS[6].dialog:'森林、潮汐与生命的信任，分别藏着三枚碎片。按 M 可以前往已经发现的区域。记得经常照顾你的伙伴。');break;
case 'exit':if(world.districtReturn){const d=world.districtReturn;world.districtReturn=null;world.load(d.area,d.room);world.returnPoint=d.point;world.pos.set(d.x,0,d.z);world.fpos.copy(world.pos);world.trail=[world.pos.clone()];}else world.leave();sync();save();return;
case 'pc':team();return;
case 'slots':slots();return;
case 'prizes':prizes();return;
case 'heal':case 'home':heal();dialog(e.id==='home'?'青岚的家':'宝可梦中心','伙伴们已经恢复全部体力。无论旅途多远，这里永远为你留着一盏灯。',undefined,e.id==='home'?'woman':'room-nurse');break;
case 'shop':shop();break;
case 'berry':if(state.berries<8){state.berries=8;save();toast('树果婆婆补满了你的树果篮。')}else toast('树果篮还是满的，记得分给伙伴哦。');break;
case 'friend':dialog('小遥','看！皮卡丘一直跟在你身后。按 F 可以和它玩耍，按 P 可以更换领队。镇口的归航风铃旁，我有件小时候的事想告诉你。',[{text:'去和伙伴玩',fn:pet},{text:'再聊聊',fn:closeModal}],'trainer-may');break;
case 'warden':if(state.stage===1){dialog(QUESTS[1].speaker,QUESTS[1].dialog,[{text:'帮助森林，开始对战',fn:()=>{closeModal();heal();startBattle('onix',10,'forest')}},{text:'先准备一下',fn:closeModal}],'woman');}else dialog('守望者 · 林音',state.stage>1?'谢谢你。森林已经安静下来了。这片林子里还有许多害羞的朋友，慢慢走，你会遇见它们。':'你也是被森林的声音吸引来的吗？先去青岚镇和大木博士聊聊吧。',undefined,'woman');break;
case 'fish':fishing();break;
case 'fisher':dialog('老渔人',QUESTS[2].dialog,[{text:'借一根鱼竿试试',fn:fishing},{text:'继续散步',fn:closeModal}],'professor');break;
case 'ranger':case 'safari-help':dialog('保育员 · 阿岚','欢迎来到翠野保育区！这里不进行战斗。靠近草地上的伙伴，投喂树果后再试着投球。每次尝试使用背包里的精灵球。'+(state.stage===3?'成功结识一位新伙伴，就能获得第三枚回响碎片。':''),[{text:'补给 5 个精灵球 · ₽ 100',fn:()=>{if(state.money<100){toast('旅费不足，可以战斗赚取。');return}state.money-=100;state.balls+=5;save();sync();closeModal();toast('获得 5 个精灵球。')}},{text:'出发探索',fn:closeModal}],'woman');break;
case 'arcade':arcade();break;
case 'pet':pet();break;
case 'guardian':if(state.stage===5){dialog(QUESTS[5].speaker,QUESTS[5].dialog,[{text:'一起回应这份心跳',fn:()=>{closeModal();heal();startBattle('mewtwo',Math.max(15,state.team[0].level+2),'final')}},{text:'先准备一下',fn:closeModal}]);}else if(state.stage===6){dialog('遗迹的旧朋友','超梦认可了你的羁绊。现在，你可以尝试与它成为伙伴。',[{text:'与超梦再会',fn:()=>{closeModal();startBattle('mewtwo',18)}},{text:'下次再见',fn:closeModal}]);}else dialog('回响之心',state.stage===6?'遗迹中的光芒温柔地回应着你。梦幻似乎还在某个角落等着你。':'三枚碎片与伙伴的心跳，将在这里重逢。');break;
case 'wild':if(world.interior&&routeIndex(world.interior)<0)return;if(routeIndex(world.interior)>=0?ROUTES[routeIndex(world.interior)].biome==='safari':state.area===3){safari(e);break}const level=[5,8,9,8,12,16][state.area]+Math.floor(Math.random()*3);seen(e.pokemon);dialog('野外相遇',`${MON[e.pokemon].name} · Lv. ${level}<br>它正在草地中活动。你可以挑战并尝试收服，也可以安静地绕过。`,[{text:'准备好了，开始对战',fn:()=>{closeModal();startBattle(e.pokemon,level,null,e)}},{text:'悄悄离开',fn:closeModal}],e.pokemon+'-front');break;
case 'story-place':storyPlace();break;case 'legendary-shrine':legendaryQuest();break;case 'lost-pokemon':case 'dream-memory':case 'hidden-spring':sideEvent(e.id);break;case 'grotto':world.load(state.area,{name:'隐秘花谷',service:'grotto'});sync();save();toast('穿过裂隙，阳光落进了一片从未见过的花谷。');break;case 'cave-return':world.load(state.area,{name:'回响石窟',service:'cave'});sync();save();break;case 'discovery':if(state.discoveries.includes(state.area)){dialog('伙伴的发现','这里已经探索过啦，换一片区域继续寻找吧。',undefined,state.team[0].id+'-front');break}state.discoveries.push(state.area);state.berries+=3;state.balls+=2;state.money+=120;state.team[0].bond=Math.min(100,state.team[0].bond+5);save();sync();dialog('伙伴找到了旅行补给！',`${MON[state.team[0].id].name}循着花香找到了树果与补给包！<br>树果 +3 · 精灵球 +2 · 旅费 +120 · 羁绊 +5<br>已探索 ${state.discoveries.length} / 6 处伙伴发现点。`,undefined,state.team[0].id+'-front');break;case 'main-road':travel(e.destination,OPPOSITE[e.side]);break;

case 'route-town':travel(e.destination,e.route);break;
case 'route-observe':observeRoute(e);break;
default:if(e.line){dialog(e.name,e.line,undefined,e.portrait||'woman');break}
}}
function shop(){modal('青岚补给商店',`<p>为下一段路，准备一点安心。</p><p>可用旅费：<b>₽ ${state.money.toLocaleString()}</b></p>${[['balls','精灵球 × 5',100,'提高收服机会：先削弱对方的体力。'],['potions','伤药 × 3',120,'每瓶恢复 35 点体力，战斗中也能使用。'],['berries','树果 × 5',80,'可以喂给伙伴，也能用于保育区。']].map(([id,n,p,t])=>`<div class="bag-row"><div><b>${n}</b><small>${t}</small></div><button class="button secondary" data-buy="${id}" data-price="${p}">₽ ${p}</button></div>`).join('')}`,'PROVISIONS');document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const p=+b.dataset.price;if(state.money<p){toast('旅费不足，完成野外对战可以赚取旅费。');return}state.money-=p;state[b.dataset.buy]+=b.dataset.buy==='potions'?3:5;save();sync();shop()})}
function map(){
 const xy=i=>[90+TOWN_GRID[i][0]*210,100+TOWN_GRID[i][1]*140];
 const edges=CONNECTIONS.map((c,i)=>{const [a,b]=c.towns.map(xy);const y=i===4?310:25;const d=i<4?`M${a} L${b}`:`M${a} L${a[0]},${y} L${b[0]},${y} L${b}`;return `<path d="${d}" fill="none" stroke="${i<4?'#b59c66':'#80aaa0'}" stroke-width="5"/><text x="${(a[0]+b[0])/2}" y="${i<4?a[1]-12:y-7}" text-anchor="middle" fill="#435e50" font-size="13">${ROUTES[i].name}</text>`}).join('');
 const nodes=AREAS.map((a,i)=>{const [x,y]=xy(i);return `<rect x="${x-62}" y="${y-19}" width="124" height="38" rx="12" fill="${i===state.area?'#315c4d':'#f4f2e4'}" stroke="#8ca58c"/><text x="${x}" y="${y+5}" text-anchor="middle" fill="${i===state.area?'white':'#315c4d'}" font-size="14">${a.name}</text>`}).join('');
 modal('森屿路图 · 北上南下，西往东来',`<p>深色地点是你所在的主区域。海岸绕行南侧，山庭绕行北侧；其余道路按地图方位直连。</p><svg viewBox="0 0 600 345" style="width:100%;background:#edf0e3;border-radius:16px" role="img" aria-label="森屿地图：右侧青岚镇与森林，中间渔港与保育区，左侧星灯街与遗迹"><path d="M90 100V240 M300 100V240 M510 100V240" stroke="#b59c66" stroke-width="5"/>${edges}${nodes}</svg><p class="map-tip">${STORY_DIRECTIONS[state.stage]}</p><div class="map-grid">${AREAS.map((a,i)=>`<button class="map-tile ${state.area===i?'active':''}" data-travel="${i}" ${i===5&&state.stage<5?'disabled':''}><b>${a.name}</b><small>${i===5&&state.stage<5?'等待主线解锁':'快速旅行'}</small></button>`).join('')}</div><h3>开阔野外通路</h3><p>三张独立地图，共九处神兽停留空地。主线后向博士领取调查，平时也可以自由穿行。</p><div class="map-grid">${WILDLANDS.map((r,i)=>`<button class="map-tile" data-wildland="${i}"><b>${r.name}</b><small>${r.towns.map(t=>AREAS[t].name).join(' ↔ ')}</small></button>`).join('')}</div><h3>沿途回信</h3>${ROUTES.map((r,i)=>`<p><b>${r.name}</b> · ${state.surveys.filter(k=>k.startsWith(i+':')).length}/3<br>${CONNECTIONS[i].towns.map(t=>AREAS[t].name+'的'+townEndpoint(i,t).name+'口').join(' ↔ ')}</p>`).join('')}`,'THE EMERALD ARCHIPELAGO');
 document.querySelectorAll('[data-travel]').forEach(b=>b.onclick=()=>travel(+b.dataset.travel));document.querySelectorAll('[data-wildland]').forEach(b=>b.onclick=()=>{const i=+b.dataset.wildland,r=WILDLANDS[i];travel(r.towns.includes(state.area)?state.area:r.towns[0]);world.goTo('wildland-gate-'+i);toast('已导航到'+r.name+'入口，走近按 E。')});
}
function team(){modal('同行的每一个你',`<p class="muted">第一位伙伴会跟随你，并首先出战。队伍最多六位，其余伙伴在后备盒。</p><div class="team-grid">${state.team.map((m,i)=>`<div class="team-tile">${img(m.id)}<h3>${MON[m.id].name} <small>Lv.${m.level}</small></h3><span class="type">${MON[m.id].type}</span> <small>羁绊 ${m.bond}</small><div class="hp-bar"><i style="width:${m.hp/m.max*100}%"></i></div><p class="muted">HP ${m.hp} / ${m.max}</p>${experienceBar(m)}${evolutionActions(m,i)}<button data-lead="${i}" ${i===0?'disabled':''}>${i===0?'正在跟随':'设为领队'}</button><button data-store="${i}" ${state.team.length===1?'disabled':''}>送入后备盒</button></div>`).join('')}</div><h3>后备盒 · ${state.box.length}</h3>${state.box.length?`<div class="team-grid">${state.box.map((m,i)=>`<div class="team-tile">${img(m.id)}<h3>${MON[m.id].name}</h3><button data-withdraw="${i}" ${state.team.length>=6?'disabled':''}>加入队伍</button></div>`).join('')}</div>`:'<p class="muted">这里还很安静。队伍满员后，新伙伴会在这里休息。</p>'}`,'YOUR COMPANIONS');bindEvolution();document.querySelectorAll('[data-lead]').forEach(b=>b.onclick=()=>{const i=+b.dataset.lead;[state.team[0],state.team[i]]=[state.team[i],state.team[0]];save();sync();team()});document.querySelectorAll('[data-store]').forEach(b=>b.onclick=()=>{if(state.team.length<=1)return;state.box.push(...state.team.splice(+b.dataset.store,1));save();sync();team()});document.querySelectorAll('[data-withdraw]').forEach(b=>b.onclick=()=>{if(state.team.length>=6)return;state.team.push(...state.box.splice(+b.dataset.withdraw,1));save();sync();team()})}
function bag(){modal('装着小小期待的背包',`<div class="bag-row"><div><b>大师球</b><small>必定收服野生宝可梦 · 博士的重复调查奖励</small></div><b>× ${state.masterBalls}</b></div><div class="bag-row"><div><b>精灵球</b><small>与野生宝可梦成为伙伴</small></div><b>× ${state.balls}</b></div><div class="bag-row"><div><b>伤药</b><small>给领队恢复 35 HP</small></div><button class="button secondary" id="bag-heal">使用 · ${state.potions}</button></div><div class="bag-row"><div><b>甜甜树果</b><small>伙伴互动与保育区投喂</small></div><b>× ${state.berries}</b></div><div class="bag-row"><div><b>老钓竿</b><small>河边和渔港可使用 · 永久</small></div><b>✓</b></div><div class="bag-row"><div><b>回响碎片</b><small>森林 · 潮汐 · 信任</small></div><b>${shardCount()} / 3</b></div><div class="actions"><button class="button" id="export">导出存档</button><button class="button secondary" id="import">导入存档</button><button class="button secondary" id="open-shop">购买补给</button></div><input id="file" type="file" accept=".json,application/json" hidden><p class="muted">存档保存在当前浏览器。换设备前，记得导出一份。</p>`,'EVERYDAY ESSENTIALS');$('#bag-heal').onclick=()=>{if(!state.potions){toast('伤药用完了。宝可梦中心可免费恢复。');return}const m=state.team[0];if(m.hp===m.max){toast('领队现在精神满满。');return}state.potions--;m.hp=Math.min(m.max,m.hp+35);save();sync();bag()};$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='森屿回响-旅程存档.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>1000000)throw Error('文件过大');const next=validate(JSON.parse(await f.text()));dialog('载入旅程','这会替换当前浏览器中的游戏进度。建议先导出当前存档。',[{text:'载入这份存档',fn:()=>{state=next;closeModal();restoreScene();save();sync();toast('欢迎回来，训练家。')}},{text:'取消',fn:bag}]);}catch{toast('无法读取这份存档，请选择有效的森屿回响 JSON 存档。')}};$('#open-shop').onclick=shop}
function dex(){modal('把每一次相遇记下来',`<p class="muted">已发现 ${state.seen.length} / ${DEX.length} · 已结识 ${state.caught.length} / ${DEX.length}。图鉴中的进化型可通过升级或星灯兑换获得。主线完成后可在博士处开启神兽调查，已发现与已收服记录会随剧情保存。</p><div class="dex-grid">${DEX.map(m=>`<div class="dex-tile ${state.caught.includes(m.id)?'':'unknown'}"><small>No. ${String(m.no).padStart(3,'0')} · ${state.caught.includes(m.id)?'已收服':state.seen.includes(m.id)?'已发现':'未发现'}</small>${img(m.id)}<p>${m.name} <span class="type">${m.type}</span></p>${LEGENDS.some(q=>q.id===m.id)?`<small>${state.legend.met.includes(m.id)?LEGENDS.find(q=>q.id===m.id).clue:state.stage<6?'主线完成后调查异象':'向大木博士领取调查线索'}</small>`:''}</div>`).join('')}</div>`,'THE POKÉDEX')}
function journal(){echoJournal();const b=document.createElement('button');b.className='button secondary';b.textContent='远方的回应 · 神兽调查 / 大师球';b.onclick=()=>research(legendAPI());document.querySelector('#modal-body').prepend(b);}
function legacyJournal(){modal('沿途的回响',`<h3>回信接力 · 把六条路连成一个故事</h3><p>${STORY_DIRECTIONS[state.stage]}</p><p>${state.relayReported?'六封回信已送到，博士正在重绘救援路图。':'记录六条路的18处发现；回应超梦后，回青岚镇把记录交给大木博士。'}</p>${RELAY_CHAPTERS.map(([title,text],i)=>`<p><b>${title}</b> · ${ROUTES[i].name}<br>${state.surveys.some(k=>k.startsWith(i+':'))?text:'沿途调查后解读这封回信。'}</p>`).join('')}<div class="bag-row"><b>支路自然观察</b><span>${state.surveys.length} / 18</span></div>${ROUTES.map((r,i)=>`<p>${r.name} · ${state.surveys.filter(k=>k.startsWith(i+':')).length}/3</p>`).join('')}<p class="muted">相遇 ${state.caught.length} · 对战胜利 ${state.battles} · 钓鱼 ${state.fished} · 保育区收服 ${state.safari}</p><div class="bag-row"><b>留下的回答</b><span>${Object.keys(state.responses).length} / 6</span></div>${Object.entries(state.responses).map(([i,choice])=>`<p>${LANDMARKS[i].name} · ${choice==='listen'?'坐下来听完了故事':'约好下一次相见'}</p>`).join('')}<div class="bag-row"><b>三圣鸟誓约</b><span>${state.legendaries.length} / 3</span></div><p>急冻鸟：微光森林花谷 · 梦之石 ${Math.min(3,state.events.filter(x=>x.endsWith(':memory')).length)} / 3<br>闪电鸟：潮汐渔港花谷 · 帮助皮皮 ${Math.min(3,state.events.filter(x=>x.endsWith(':rescue')).length)} / 3<br>火焰鸟：回响遗迹花谷 · 泉水休息 ${Math.min(3,state.events.filter(x=>x.endsWith(':spring')).length)} / 3</p>${QUESTS.map((q,i)=>`<div class="journal-row ${i<state.stage?'done':''}"><span>${i<state.stage?'✓':i===state.stage?'◈':'○'}</span><div><h3>${q.title} ${i===state.stage?'· 当前':''}</h3><p>${q.text}</p><small>${AREAS[q.area].name} · ${q.goal}</small></div></div>`).join('')}`,'YOUR FIELD JOURNAL')}
const panels={map,team,bag,dex,journal};
function ensureAudio(){audioCtx??=new AudioContext();if(!audioGain){audioGain=audioCtx.createGain();audioGain.gain.value=.46;audioGain.connect(audioCtx.destination)}return audioCtx}
const pitch=(semitones,base=261.63)=>base*Math.pow(2,semitones/12);
function playTone(freq,dur=.12,type='sine',gain=.02){if(!music||!audioCtx)return;const t=audioCtx.currentTime,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g).connect(audioGain||audioCtx.destination);o.start(t);o.stop(t+dur+.03)}
function tone(freq=440,dur=.12,type='sine'){if(!music)return;ensureAudio();playTone(freq,dur,type,.035)}
function trackForScene(){if(battle)return battle.story==='final'?'final':'battle';if(!world)return'town';if(wildlandIndex(world.interior)>=0)return WILDLANDS[wildlandIndex(world.interior)].music;if(routeIndex(world.interior)>=0)return ROUTE_MUSIC[routeIndex(world.interior)];if(world.interior){switch(world.interior.service){case'echo-district':return ['town','fallarbor-town','driftveil-city','safari',state.echo.period==='night'?'black-city':'arcade','ruin'][state.area];case'cave':return'mt-moon';case'grotto':return'ever-grande';case'heal':return'center';case'shop':return'shop';case'lab':return'lab';case'arcade':return'arcade';case'ranger':return'safari';default:return'home'}}return ['town','forest','coast','safari','arcade','ruin'][state.area]||'town'}
function selectedTrackId(){return musicChoice==='auto'?trackForScene():musicChoice}
function updateMusicUI(){const id=selectedTrackId(),track=TRACKS[id]||TRACKS.town,select=$('#music-select'),now=$('#music-now');$('#sound span').textContent=music?'声音开启':'声音关闭';if(select){if(!select.options.length){select.innerHTML=MUSIC.map(track=>`<option value="${track.id}">${track.name}</option>`).join('');select.onchange=()=>{cancelJingle();musicChoice=select.value;world?.keys.clear();localStorage.setItem(MUSIC_KEY,musicChoice);currentTrack=null;musicStep=0;updateMusicUI();if(music){scheduleMusic();tone(880,.08,'triangle')}}}select.value=musicChoice}if(now)now.textContent=musicChoice==='auto'?`随场景 · ${track.name}`:track.name}
function playMusicStep(){if(!music)return;ensureAudio();const id=selectedTrackId(),track=TRACKS[id]||TRACKS.town;if(currentTrack!==id){currentTrack=id;musicStep=0;updateMusicUI()}const step=musicStep++,melody=track.melody[step%track.melody.length]+track.root+12,bass=track.bass[Math.floor(step/2)%track.bass.length]+track.root-12;playTone(pitch(melody),.2,track.wave,.024);if(step%2===0)playTone(pitch(bass),.34,'triangle',.018);if(step%4===2)playTone(pitch(melody+7),.12,'square',.009);if(track.accent===3&&step%2)playTone(1760,.035,'square',.009);if(track.accent===5&&step%8===0)playTone(pitch(track.root+24),.52,'sine',.012)}
function stopSceneAudio(){if(bgmAudio){bgmAudio.pause();bgmAudio.currentTime=0}bgmAudio=null;bgmTrack=null}
function playSceneAudio(){const id=selectedTrackId(),src=LICENSED_AUDIO[id];if(!src){stopSceneAudio();return false}if(bgmAudio&&bgmTrack===id&&!bgmAudio.paused&&!bgmAudio.error)return true;stopSceneAudio();bgmAudio=new Audio(src);bgmAudio.loop=true;bgmAudio.volume=.78;bgmTrack=id;currentTrack=id;const active=bgmAudio;const fallback=()=>{if(active!==bgmAudio||!music||musicJingle)return;stopSceneAudio();currentTrack=id;startFallbackMusic()};active.onerror=fallback;active.play().catch(fallback);updateMusicUI();return true}
function playJingle(src,limit){if(!music)return;clearTimeout(audioTimer);audioTimer=null;clearTimeout(jingleTimer);musicJingle=true;stopSceneAudio();victoryAudio?.pause();const active=victoryAudio=new Audio(src);active.volume=.82;const finish=()=>{if(active!==victoryAudio||!musicJingle)return;clearTimeout(jingleTimer);active.pause();musicJingle=false;if(music)scheduleMusic()};active.onended=finish;active.onerror=finish;jingleTimer=setTimeout(finish,limit);active.play().catch(finish)}
function playVictoryMusic(){playJingle(VICTORY_AUDIO,11000)}
function playBadgeMusic(){playJingle(BADGE_AUDIO,9000)}
function cancelJingle(){clearTimeout(jingleTimer);victoryAudio?.pause();musicJingle=false}
function startFallbackMusic(){clearTimeout(audioTimer);if(!music||musicJingle)return;ensureAudio();audioCtx.resume().catch(()=>{});const tick=()=>{if(!music||musicJingle||bgmAudio)return;const track=TRACKS[selectedTrackId()];const fallback=track?.melody?track:TRACKS.town;const note=fallback.melody[musicStep++%fallback.melody.length]+fallback.root+12;playTone(pitch(note),.2,fallback.wave,.024);audioTimer=setTimeout(tick,30000/fallback.bpm)};tick()}
function scheduleMusic(){clearTimeout(audioTimer);audioTimer=null;if(!music||musicJingle)return;if(!playSceneAudio())startFallbackMusic()}
function setupMusicSelect(){const select=$('#music-select');if(!select)return;select.innerHTML=MUSIC.map(track=>`<option value="${track.id}">${track.name}</option>`).join('');select.value=musicChoice;select.onchange=()=>{cancelJingle();musicChoice=select.value;world?.keys.clear();localStorage.setItem(MUSIC_KEY,musicChoice);currentTrack=null;musicStep=0;updateMusicUI();if(music){scheduleMusic();tone(880,.08,'triangle')}};updateMusicUI()}
function updateMusic(){const scene=JSON.stringify([state.area,world?.interior?.name||null,world?.interior?.service||null,!!battle,world?.interior?.service==='echo-district'?state.echo.period:null]);if(lastMusicScene!==null&&scene!==lastMusicScene){musicChoice='auto';cancelJingle()}lastMusicScene=scene;if(music&&!musicJingle&&(selectedTrackId()!==currentTrack||(!bgmAudio&&!audioTimer)||bgmAudio?.paused||bgmAudio?.error)){currentTrack=null;musicStep=0;scheduleMusic()}updateMusicUI()}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&music){audioCtx?.resume().catch(()=>{});updateMusic()}});
document.addEventListener('pointerdown',()=>{if(music){audioCtx?.resume().catch(()=>{});if(!musicJingle&&(!bgmAudio||bgmAudio.paused))scheduleMusic()}},{passive:true});
function toggleMusic(){music=!music;if(music){ensureAudio();audioCtx.resume();currentTrack=null;musicStep=0;scheduleMusic()}else{clearTimeout(audioTimer);clearTimeout(jingleTimer);audioTimer=null;musicJingle=false;stopSceneAudio();victoryAudio?.pause()}updateMusicUI()}
function pet(){const m=state.team[0],n=MON[m.id].name;modal(`和${n}的小小约会`,`<div class="mini-stage">${img(m.id)}</div><p style="text-align:center">${n}${m.bond>50?'开心地蹭了蹭你的手。':'歪着脑袋，期待地看着你。'} <br><small>羁绊 ${m.bond} / 100</small></p><div class="actions" style="justify-content:center"><button class="button" id="feed">喂一颗树果 · ${state.berries}</button><button class="button secondary" id="stroke">摸摸脑袋</button><button class="button gold" id="rhythm">心跳节拍小游戏</button></div><p class="muted">配合伙伴的节奏，在绿色区域按下按钮。连续命中三次，就完成挑战。</p>`,'BETTER TOGETHER');$('#feed').onclick=()=>{if(!state.berries){toast('树果用完了，可以去小铺补充。');return}state.berries--;m.bond=Math.min(100,m.bond+8);m.hp=Math.min(m.max,m.hp+15);save();sync();pet();tone(784,.2)};$('#stroke').onclick=()=>{m.bond=Math.min(100,m.bond+1);save();sync();$('#stroke').textContent='它开心地眯起了眼睛 ♡';$('#stroke').disabled=true;tone(660,.2)};$('#rhythm').onclick=()=>timingGame('rhythm')}
function timingGame(kind){const isFish=kind==='fish';let hits=0,miss=0,phase=0,raf,finished=false;const speed=isFish?1.5:2;modal(isFish?'听，鱼漂动了':'心跳，慢慢靠近',`<div class="mini-stage">${img(isFish?'magikarp':state.team[0].id)}</div><p id="mini-info" style="text-align:center">${isFish?'等游标进入绿色区域，立刻收竿。':'在绿色区域按下「回应」，连续命中 3 次。'}</p><div class="timing-track"><div class="timing-zone"></div><div class="timing-cursor"></div></div><div class="actions" style="justify-content:center"><button class="button" id="timing-hit">${isFish?'收竿！':'回应伙伴'} <kbd>空格</kbd></button></div><p class="muted">${isFish?'一次命中即可钓起伙伴，失败也可以重新抛竿。':'失误会清空连续命中次数，但你可以随时再试。'}</p>`,isFish?'A QUIET MOMENT BY THE WATER':'HEARTBEAT');const start=performance.now();mini={kind,hit:()=>$('#timing-hit')?.click()};const tick=now=>{phase=(Math.sin((now-start)/1000*speed*2)+1)/2;const cursor=$('.timing-cursor');if(cursor)cursor.style.left=(phase*98)+'%';raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick);modalCleanup=()=>{cancelAnimationFrame(raf);finished=true;mini=null};$('#timing-hit').onclick=()=>{if(finished)return;const success=phase>=.39&&phase<=.61;if(success){hits++;tone(660+hits*110,.15);if(isFish||hits>=3){finished=true;cancelAnimationFrame(raf);if(isFish){const pool=state.area===2?['magikarp','psyduck','lapras','dratini','squirtle']:['magikarp','psyduck','squirtle'];const id=pool[Math.floor(Math.random()*pool.length)];state.fished++;const where=catchMon(id,6+Math.floor(Math.random()*4));const advanceStory=state.stage===2&&state.area===2;if(advanceStory)advance(2);dialog('好大的一阵水花！',`你钓起了${MON[id].name}，它${where}！${advanceStory?'它衔着旧浮标旁的蓝色碎片！老人接过那块铜牌，认出了潮生的名字。他指向保育区：“最后一枚由阿岚保管。潮生如今在隐秘花谷照料迷路的伙伴，沿岩窟进去，就能听见它。”':''}`,[{text:'再钓一次',fn:fishing},{text:'回到岸边',fn:closeModal}]);}else{const m=state.team[0];m.bond=Math.min(100,m.bond+15);state.petWins++;state.coins+=25;const adv=state.stage===4&&state.area===4;if(adv)advance(4);save();sync();dialog('同一个心跳',`${MON[m.id].name}兴奋地跳了起来！羁绊 +15，获得 25 枚游戏代币。${adv?'小遥在第三拍之后停下。你和伙伴的下一次回应，恰好填进那段空白。三枚碎片终于亮起，不再相互盖住声音。石头里传来一句很轻的“收到”。遗迹的道路已开启。':''}`,[{text:'太棒了，继续冒险',fn:closeModal},{text:'再玩一次',fn:()=>timingGame('rhythm')}]);}}else $('#mini-info').textContent=`回应成功！${hits} / 3 · 就是这个节奏。`}else{hits=0;miss++;tone(220,.12);$('#mini-info').textContent=isFish?'鱼儿溜走了，找准下一次时机再收竿。':'节拍错开了一点点。慢慢来，重新开始 0 / 3。'}}}
function fishing(){if(state.area!==2&&!world.entities.some(e=>e.id==='fish'&&Math.hypot(e.x-world.pos.x,e.z-world.pos.z)<4)){toast('走到河畔钓点，或者前往潮汐渔港。');return}timingGame('fish')}
function safari(e){seen(e.pokemon);let bait=0,tries=0;const id=e.pokemon;function show(message='草丛里的它正在观察你。'){modal('一次温柔的相遇',`<div class="mini-stage">${img(id)}</div><p style="text-align:center"><b>${MON[id].name}</b> · ${message}</p><div class="actions" style="justify-content:center"><button class="button secondary" id="bait">投喂树果 · ${state.berries}</button><button class="button" id="safari-ball">轻轻投球 · ${state.balls}</button><button class="button secondary" id="safari-leave">悄悄离开</button></div><p class="muted">保育区内不战斗。树果能提升信任，每次投球消耗一枚精灵球。</p>`,'VERDANT SANCTUARY');$('#bait').onclick=()=>{if(!state.berries){toast('没有树果了，去商店补给吧。');return}state.berries--;bait=Math.min(3,bait+1);save();show('它靠近了一些，似乎放松了警惕。')};$('#safari-ball').onclick=()=>{if(!state.balls){toast('精灵球用完了。管理员可以提供补给。');return}state.balls--;tries++;if(Math.random()<.32+bait*.2+tries*.08){const where=catchMon(id,8+Math.floor(Math.random()*4));state.safari++;const adv=state.stage===3&&state.area===3&&!world.interior;if(adv)advance(3);removeWild(e);save();dialog('它愿意与你同行',`${MON[id].name}${where}。${adv?'阿岚看着它主动靠近你，交出了第三枚碎片：“它自己选了你。记住这一刻。”三片石头却只传出杂乱的旧铃声。阿岚请你去星灯街找小遥——她一直在整理当年的救援铃谱。':''}`,[{text:'谢谢你，我的新朋友',fn:closeModal}]);}else{save();show('它从球里跳了出来，但仍愿意留在这里。')}};$('#safari-leave').onclick=closeModal}show()}
function arcade(){modal('星灯娱乐城',`<p>在冒险中休息一下。这里的代币只用于小游戏，没有现金兑换。</p><div class="slots"><span>✧</span><span>◒</span><span>✧</span></div><p style="text-align:center">你的游戏代币：<b>${state.coins}</b></p><div class="actions" style="justify-content:center"><button class="button gold" id="slots-open">幸运转轮</button><button class="button" id="arcade-rhythm">伙伴节奏挑战</button><button class="button secondary" id="prizes">兑换小惊喜</button></div><p class="muted">完成一次伙伴节奏挑战可赚取 25 代币。无需消费旅费。</p>`,'STARLIGHT GAME CORNER');$('#slots-open').onclick=slots;$('#arcade-rhythm').onclick=()=>timingGame('rhythm');$('#prizes').onclick=prizes}
function slots(){let rolling=false,interval=null;modal('今晚的幸运色',`<p class="muted">三格相同获得 60 代币，任意两格相同获得 15 代币。每次 5 代币。</p><div class="slots" id="reels">${['pikachu','eevee','clefairy'].map(id=>`<span>${img(id)}</span>`).join('')}</div><p id="slots-result" style="text-align:center">代币余额：${state.coins}</p><div class="actions" style="justify-content:center"><button class="button gold" id="spin">转动 · 5 代币</button><button class="button secondary" id="slots-back">返回娱乐城</button></div>`,'A LITTLE BIT OF LUCK');const pool=['pikachu','eevee','clefairy','bulbasaur'];let timeout;modalCleanup=()=>{clearInterval(interval);clearTimeout(timeout)};$('#spin').onclick=()=>{if(rolling)return;if(state.coins<5){$('#slots-result').textContent='代币不足。伙伴节奏挑战可以免费赚取代币。';return}rolling=true;state.coins-=5;save();$('#spin').disabled=true;$('#slots-back').disabled=true;let r=[];interval=setInterval(()=>{r=Array.from({length:3},()=>pool[Math.floor(Math.random()*pool.length)]);$('#reels').innerHTML=r.map(id=>`<span>${img(id)}</span>`).join('');tone(440,.04)},80);timeout=setTimeout(()=>{clearInterval(interval);const reward=new Set(r).size===1?60:new Set(r).size===2?15:0;state.coins+=reward;save();$('#slots-result').textContent=(reward?`小小幸运！获得 ${reward} 代币。`:'差一点点，下次也许会更幸运。')+` 余额：${state.coins}`;rolling=false;$('#spin').disabled=false;$('#slots-back').disabled=false},1100)};$('#slots-back').onclick=arcade}
function prizes(){const ids=['eevee','vaporeon','jolteon','flareon','raichu','articuno','zapdos','moltres'];modal('星灯的小惊喜',`<p>代币余额：${state.coins}。这里的伙伴正等着新的训练家。</p><div class="team-grid">${ids.map((id,i)=>`<div class="team-tile">${img(id)}<h3>${MON[id].name}</h3><button data-prize="${id}" data-price="${i<5?100:250}">${i<5?100:250} 代币 · 邀请</button></div>`).join('')}</div>`,'STARLIGHT EXCHANGE');document.querySelectorAll('[data-prize]').forEach(b=>b.onclick=()=>{const p=+b.dataset.price;if(state.coins<p){toast('代币还不够，和伙伴玩节奏游戏就能获得。');return}state.coins-=p;catchMon(b.dataset.prize,12);prizes()})}
function removeWild(e){if(!e)return;if(!battle&&state.area!==3)playVictoryMusic();e.mesh.visible=false;world.entities=world.entities.filter(x=>x!==e);world.wild=world.wild.filter(x=>x!==e);const candidates=(e.habitatPool|| (routeIndex(world.interior)>=0?world.wild.map(x=>x.pokemon):AREAS[state.area].wild)).filter(id=>id!==e.pokemon);setTimeout(()=>{if(world.area!==state.area||world.land!==e.mesh.parent)return;const id=candidates[Math.floor(Math.random()*candidates.length)]||e.pokemon;world.respawnWild(e,id)},18000)}

function startBattle(id,level,story=null,entity=null){if(battle)return;const first=state.team.findIndex(m=>m.hp>0);if(first<0){dialog('伙伴需要休息','队伍已经没有体力了。先回青岚镇的宝可梦中心恢复吧。',[{text:'回镇里恢复',fn:()=>{travel(0);heal()}}]);return}if(first>0)[state.team[0],state.team[first]]=[state.team[first],state.team[0]];seen(id);battle={enemy:makeMon(id,level),story,entity,log:story?`${MON[id].name}回应了你的挑战。`:`野生的${MON[id].name}出现了！`,turns:0};world.paused=true;world.keys.clear();busy=false;$('#battle').hidden=false;$('#battle').dataset.biome=wildlandIndex(world.interior)>=0?WILDLANDS[wildlandIndex(world.interior)].biome:routeIndex(world.interior)>=0?ROUTES[routeIndex(world.interior)].biome:world.interior?.service==='cave'?'cave':world.interior?.service==='grotto'?'garden':['town','forest','coast','safari','city','ruin'][state.area];$('#battle').dataset.legendary=story?.startsWith('legendary:')||story?.startsWith('roaming:')?'true':'false';sync();busy=true;renderBattle();const opening=battle;Promise.all([battleFX('sendout',{type:MON[state.team[0].id].type}),LEGENDS.some(q=>q.id===id)||story?.startsWith('legendary:')?legendBattleFX(id,'entrance'):Promise.resolve()]).finally(()=>{if(battle===opening){busy=false;renderBattle()}})}
function renderBattle(menu='moves'){if(!battle)return;const p=state.team[0],e=battle.enemy,pm=MON[p.id],em=MON[e.id],moves=MOVES[pm.type]||MOVES['一般'];$('#battle').innerHTML=`<div class="battle-top">${battle.story?.startsWith('trainer:')?'训练师切磋':battle.story?.startsWith('roaming:')?'神兽相遇':battle.story?'回响试炼':'野外相遇'} / ${world.interior?.name||AREAS[state.area].name}</div><div class="battle-stat enemy"><b>${em.name}</b><span>Lv. ${e.level} · ${em.type}</span><div class="hp-bar"><i style="width:${e.hp/e.max*100}%"></i></div><small>${e.hp} / ${e.max}</small></div>${img(e.id,'front','battle-mon enemy')}${img(p.id,'back','battle-mon ally')}<div class="battle-stat ally"><b>${pm.name}</b><span>Lv. ${p.level} · ${pm.type}</span><div class="hp-bar"><i style="width:${p.hp/p.max*100}%"></i></div><small>${p.hp} / ${p.max}</small>${experienceBar(p)}</div><div class="battle-bottom"><div class="battle-log">${battle.log}</div><div class="battle-actions">${menu==='moves'?`<button data-battle="attack">${moves[0]} · ${pm.type}</button><button data-battle="quick">电光一闪 · 一般</button><button data-battle="catch" ${battle.story&&!battle.story.startsWith('roaming:')?'disabled':''}>精灵球 × ${state.balls}</button><button data-battle="more">背包 / 换人 / 逃跑</button>`:menu==='more'?`<button data-battle="master" ${battle.story&&!battle.story.startsWith('roaming:')?'disabled':''}>大师球 × ${state.masterBalls}</button><button data-battle="potion">伤药 × ${state.potions}</button><button data-battle="switch">更换伙伴</button><button data-battle="run" ${battle.story&&!battle.story.startsWith('roaming:')?'disabled':''}>逃离战斗</button><button data-battle="back">返回招式</button>`:state.team.map((m,i)=>`<button data-switch="${i}" ${i===0||m.hp<=0?'disabled':''}>${MON[m.id].name} ${m.hp} HP</button>`).join('')+`<button data-battle="back">返回</button>`}</div></div>`;document.querySelectorAll('[data-battle]').forEach(b=>{b.disabled||=busy;b.onclick=()=>battleAction(b.dataset.battle)});document.querySelectorAll('[data-switch]').forEach(b=>{b.disabled||=busy;b.onclick=()=>battleAction('switch:'+b.dataset.switch)})}
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function battleAction(action){if(!battle||busy)return;if(action==='more'){renderBattle('more');return}if(action==='back'){renderBattle();return}if(action==='switch'){renderBattle('switch');return}if(action==='run'){endBattle(false);toast('你和伙伴安全离开了。');return}
 busy=true;renderBattle();const p=state.team[0],e=battle.enemy;let log='';
 if(action==='catch'||action==='master'){const master=action==='master';if(!(master?state.masterBalls:state.balls)){busy=false;battle.log=master?'大师球用完了。完成博士的生态调查可再次获得。':'精灵球用完了。去小铺补充一些吧。';renderBattle();return}if(battle.story&&!battle.story.startsWith('roaming:')){busy=false;renderBattle();return}if(master)state.masterBalls--;else state.balls--;save();const chance=.18+(1-e.hp/e.max)*.68+(p.level-e.level)*.015;const success=master||Math.random()<chance;battle.log='精灵球晃了一下……又晃了一下……';renderBattle();tone(520,.15);await battleFX('catch');await delay(300);if(success){const id=e.id,where=catchMon(id,e.level);if(battle.entity?.legend)dismissLegend(world,battle.entity);else removeWild(battle.entity);endBattle(false);toast(`${MON[id].name}${where}！`);return}log='它从精灵球里挣脱了！';
 }else if(action==='potion'){if(!state.potions||p.hp===p.max){busy=false;battle.log=state.potions?'伙伴的体力已经是满的。':'伤药用完了。';renderBattle();return}await battleFX('heal');state.potions--;p.hp=Math.min(p.max,p.hp+35);log=`${MON[p.id].name}恢复了体力。`;
 }else if(action.startsWith('switch:')){const i=+action.split(':')[1];if(!state.team[i]||!state.team[i].hp){busy=false;return}[state.team[0],state.team[i]]=[state.team[i],state.team[0]];log=`上吧，${MON[state.team[0].id].name}！`;battle.log=log;renderBattle();await battleFX('sendout',{type:MON[state.team[0].id].type,both:false});
 }else{const type=action==='quick'?'一般':MON[p.id].type,eff=effectiveness(type,MON[e.id].type),damage=Math.max(eff===0?0:1,Math.round((10+p.level*.95)*eff*(.9+Math.random()*.2)));battle.log=`${MON[p.id].name}使出${action==='quick'?'电光一闪':(MOVES[type]||MOVES['一般'])[0]}！`;renderBattle();await battleFX('attack',{type,quick:action==='quick',immune:eff===0});e.hp=Math.max(0,e.hp-damage);log=`${MON[p.id].name}使出${action==='quick'?'电光一闪':(MOVES[type]||MOVES['一般'])[0]}！造成 ${damage} 伤害。${eff>1?'效果绝佳！':eff<1?'效果不太理想。':''}`;tone(eff>1?880:520,.13,'triangle');}
 battle.log=log;renderBattle();save();sync();if(e.hp<=0){await battleFX('faint',{side:'enemy'});endBattle(true);return}await delay(700);if(!battle)return;const active=state.team[0],eff=effectiveness(MON[e.id].type,MON[active.id].type);const damage=Math.max(eff===0?0:1,Math.round((6+e.level*.65)*eff*(.85+Math.random()*.3)));battle.log=`${MON[e.id].name}使出${(MOVES[MON[e.id].type]||MOVES['一般'])[0]}！`;renderBattle();await battleFX('attack',{side:'enemy',type:MON[e.id].type,immune:eff===0});if(LEGENDS.some(q=>q.id===e.id)||battle.story?.startsWith('legendary:'))await legendBattleFX(e.id,'attack');active.hp=Math.max(0,active.hp-damage);battle.turns++;battle.log=log+` ${MON[e.id].name}反击，造成 ${damage} 伤害。`;if(active.hp<=0){await battleFX('faint',{side:'ally'});const next=state.team.findIndex(m=>m.hp>0);if(next<0){battle.log='伙伴们已经尽力了……先回去休息吧。';renderBattle();await delay(900);endBattle(false);travel(0);heal();toast('你被送回青岚镇，伙伴已经恢复。可以再挑战一次。');return}[state.team[0],state.team[next]]=[state.team[next],state.team[0]];battle.log=`${MON[active.id].name}暂时失去战斗能力。${MON[state.team[0].id].name}接替上场！`}busy=false;save();sync();renderBattle();}
function endBattle(win){const b=battle;if(!b)return;battle=null;busy=false;$('#battle').hidden=true;world.paused=false;if(win){state.battles++;state.money+=100+b.enemy.level*10;const evolutions=[];state.team.forEach(m=>{for(const [old,id] of gainExperience(m,40+b.enemy.level*5)){seen(id);if(!state.caught.includes(id))state.caught.push(id);evolutions.push(`${MON[old].name}进化成了${MON[id].name}`)}});if(!b.entity?.legend)removeWild(b.entity);if(b.story?.startsWith('trainer:')&&!state.legend.wins.includes(b.story.slice(8)))state.legend.wins.push(b.story.slice(8));if(b.story?.startsWith('legendary:')){const id=b.story.split(':')[1];if(!state.legendaries.includes(id)){state.legendaries.push(id);const where=catchMon(id,b.enemy.level);dialog('誓约完成',`${MON[id].name}认可了你一路上的行动，${where}！<br>三圣鸟誓约 ${state.legendaries.length} / 3。`,undefined,id+'-front')}}else if(b.story==='forest'&&state.stage===1){advance(1);state.badges=1;state.balls+=8;dialog('森林再次安静下来','大岩蛇缓缓退回岩壁。林音趁机从树根下取出一块写着「潮生」的铜牌，还有第一枚绿色碎片。原来它守着的是当年避雨棚里留下的东西。林音敲了三下棚柱，它终于放松下来。<br><br>“去渔港问问这个名字吧。我留下修好这座棚，等你们的消息。”你得到 8 枚精灵球。',[{text:'前往潮汐渔港',fn:()=>travel(2)},{text:'再看看森林',fn:closeModal}],'woman')}else if(b.story==='final'&&state.stage===5){advance(5);state.badges=2;catchMon('mew',15);heal();dialog('每一次相遇，都是回响','超梦收起力量。碎片里最后一声“有人在吗”仍在重复。你没有再碰核心，只蹲下来，等伙伴走到身边。<br><br>“有。我们在这里。”<br><br>林音从避雨棚敲来三声，渔港的旧浮标接了一声，驿站与灯塔也依次回答。旧日的求救终于有了结尾。梦幻循着这些新声音来到你身旁，愿意同行。<br><br>森林留下走过的痕迹，岛屿让相隔的人听见彼此。所谓回响，不是让过去永远重复，而是有人听见之后，愿意回答。<b>这就是森屿回响。</b><br><br>主线故事已完成。回各地风铃旁看看吧，你留下的话，也有人记得。',[{text:'继续我们的旅程',fn:closeModal},{text:'回看旅程手记',fn:journal}]);}else toast(`对战胜利！获得旅费和全队经验。${evolutions.length?evolutions.join('，'):'伙伴们又成长了一点。'}`)}save();sync();$('#world').focus()}
function help(){modal('一起出发吧，训练家',`<p>这是一个可通关的六区域同人短篇冒险。沿右侧的故事提示，收集三枚回响碎片，最后挑战遗迹守护者。</p><div class="bag-row"><b>移动 / 奔跑</b><span>WASD、方向键 / Shift</span></div><div class="bag-row"><b>交谈 / 调查 / 野生对战</b><span>靠近目标，按 E</span></div><div class="bag-row"><b>地图 / 队伍 / 背包</b><span>M / P / B</span></div><div class="bag-row"><b>图鉴 / 手记 / 伙伴互动</b><span>G / J / F</span></div><div class="bag-row"><b>小游戏 / 关闭菜单</b><span>空格 / Esc</span></div><p>点击地面或地点标签也可以移动；手机可使用地图下方的方向键。地图上方「建筑 / 设施」可导航到门口，靠近按 E 进入；室内柜台提供服务，下方出口返回原门口。走不过去时，请绕开树木和建筑。打开世界地图，可以随时在已开放区域间旅行。</p><p>战斗为简化的回合制规则，包含属性克制、收服、换人、伤药、全队经验与部分等级进化。保育区采用投喂与投球。宝可梦中心免费恢复。</p><p class="muted">版本 0.3 · ${DEX.length} 种宝可梦 · 原创短篇故事。不是火红或 Gamma Emerald 的完整复刻。场景素材来自你提供的 fire_red，角色与宝可梦来自新增的 pokefirered-master。音乐选自本地宝可梦音乐集。主线完成后与博士交谈，开启跨世代神兽调查和可重复的大师球委托。</p>`,'HOW TO PLAY')}
async function boot(){try{document.body.appendChild($('#toast'));await prepareSources();world=new World($('#world'),interact);restoreScene();sync();$('#loading').hidden=true;if(loadError)toast('旧存档无法读取，原始数据已保护，自动保存已暂停。');$('#close').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal()});document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>{if(!battle)panels[b.dataset.panel]()});$('#save').onclick=selectSaveSlot;$('#new-game').onclick=newGame;$('#sound').onclick=toggleMusic;$('#help').onclick=help;$('#pet-shortcut').onclick=()=>{if(!battle)pet()};$('#track').onclick=()=>{if(battle)return;const q=QUESTS[state.stage];if(world.interior){world.leave();sync();save()}if(state.area!==q.area){travel(q.area);toast(`故事目标：${q.goal}`)}else if(!world.goTo(q.target))toast(q.goal)};$('#camera').onclick=()=>{world.zoom=world.zoom===1.12?1.4:1.12;world.resize()};$('#touch-e').onclick=interact;document.querySelectorAll('[data-dir]').forEach(b=>{const key=b.dataset.dir.toLowerCase();b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);world.keys.add(key)});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>world.keys.delete(key))});
 document.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(e.target.matches('select,input,textarea'))return;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(key)&&e.target.tagName!=='INPUT')e.preventDefault();if(key==='escape'){if(!$('#modal').hidden)closeModal();return}if(!$('#modal').hidden){if(key===' '&&mini&&!e.repeat)mini.hit();if(key==='tab'){const focusable=[...$('#modal').querySelectorAll('button:not([disabled]),input:not([hidden])')];const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}return}if(battle)return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','shift'].includes(key)){world.keys.add(key);return}if(e.repeat)return;if(key==='e'||key===' ')interact();else if(key==='f')pet();else if({m:1,p:1,b:1,g:1,j:1}[key])panels[{m:'map',p:'team',b:'bag',g:'dex',j:'journal'}[key]]()});document.addEventListener('keyup',e=>world.keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>world.keys.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden)world.keys.clear()});setInterval(()=>{if(!battle)save()},30000);window.addEventListener('beforeunload',()=>save());
 // Read-only diagnostics support repeatable smoke checks without altering a player's save.
 window.echoDiagnostics=()=>({ready:!!world,echo:JSON.parse(JSON.stringify(state.echo)),area:state.area,stage:state.stage,position:{x:world.pos.x,z:world.pos.z},interior:world.interior,returnPoint:world.returnPoint,playerFrame:world.player.userData.frame,playerDirection:world.playerDir,playerFlip:world.player.material.map.repeat.x<0,turning:world.player.userData.turning,follower:{x:world.fpos.x,z:world.fpos.z,direction:world.followerDirection,frame:world.follower.userData.frame,moving:!!world.followerMoving},team:state.team.map(m=>({...m})),entities:world.entities.map(e=>({id:e.id,x:e.x,z:e.z,pokemon:e.pokemon,portal:e.portal,service:e.service,name:e.name,route:e.route,point:e.point,destination:e.destination,side:e.side,returnOffset:e.returnOffset,actor:e.actor?{x:e.actor.position.x,z:e.actor.position.z}:null})),obstacles:world.obstacles.map(o=>({x:o.x,z:o.z,w:o.w,d:o.d,kind:o.kind,entity:o.entity})),layoutWarnings:world.layoutWarnings||[],battle:!!battle,paused:world.paused,saveKey:KEY,renderer:world.renderer.info.render});
 }catch(e){console.error(e);$('#loading').innerHTML='<h2>这片岛屿暂时没有醒来</h2><p>请使用支持 WebGL 的浏览器，并通过 start.cmd 启动本地服务器。</p><button onclick="location.reload()">重新尝试</button>'}}
function buildings(){
 if(battle)return;
 const stations=world.entities.filter(e=>world.interior?e.id!=='wild':e.portal||e.id==='story-place'||e.id==='main-road'||e.id==='regional-memory'||e.id==='echo-district'||e.id==='wild'||e.id==='legend-survey');
 modal(routeIndex(world.interior)>=0||wildlandIndex(world.interior)>=0?'沿途探索':world.interior?'室内设施':'建筑与道路',`<p>选择目的地自动走近，然后按 E 进入或使用。建筑内下方的出口可以返回原来的门口。</p><div class="map-grid">${stations.map((e,i)=>`<button class="map-tile" data-station="${i}"><b>${escapeHTML(e.name)}</b><small>${/^(route|wildland)-/.test(e.service||'')?'探索支路':e.portal?'进入建筑':e.id==='exit'?'返回室外':'使用设施'}</small></button>`).join('')}</div>${stations.length?'':'<p>这片区域没有建筑。打开世界地图可前往附近城镇。</p>'}`,'BUILDINGS & SERVICES');
 document.querySelectorAll('[data-station]').forEach(b=>b.onclick=()=>{const e=stations[+b.dataset.station];closeModal();world.goTo(e)});
}
function restoreScene(){world.echoState=state.echo;world.storyStage=state.stage;const room=state.room;world.districtReturn=room?.districtReturn||null;world.load(state.area,room?{name:room.name,service:room.service}:null);if(room)world.returnPoint={...room.returnPoint};}
// District events use the existing state/save lifecycle. Main-story stage numbers remain stable.
function echoRecord(text){state.echo.log.push(text);state.echo.log=state.echo.log.slice(-60);save();sync();}
function echoRefresh(){const room=world.interior,point=world.returnPoint,pos=world.pos.clone();world.echoState=state.echo;world.load(state.area,room);world.returnPoint=point;if(world.canMove(pos.x,pos.z)){world.pos.copy(pos);world.fpos.copy(pos);world.trail=[pos.clone()]}sync();save();}
function echoComplete(key,text){if(!state.echo.milestones.includes(key)){state.echo.milestones.push(key);state.money+=120;echoRecord(text+' · 旅费 +120')}echoRefresh();dialog('有人听见了，也有人回答了',text,undefined,state.team[0].id+'-front');}
function echoInteract(e){
 if(e.id==='echo-building'){world.districtReturn={area:state.area,room:{...world.interior},point:{...world.returnPoint},x:world.pos.x,z:world.pos.z};world.enter({...e,name:e.name.replace('进入 · ', '')});sync();save();return true;}
 if(e.id==='echo-district'){world.enter(e);sync();save();toast('进入故事街区 · 南侧出口返回原区域');return true;}
 if(!e.id.startsWith('echo-'))return false;
 if(e.id==='echo-hub')echoHub();
 else if(e.id==='echo-character'){
  const c=CHARACTERS[e.character],late=state.echo.milestones.includes(['relay','shelter','relay','migration','overdrive','gubo'][state.area]);
  dialog(c.name,(late?c.late:c.early)+'<br><br>同行伙伴：'+MON[c.partner].name,[{text:'听听同行的理由',fn:()=>{if(!state.echo.episodes.includes(e.character)){state.echo.episodes.push(e.character);echoRecord(c.name+'：'+c.goal)}dialog(c.name,c.goal+'。<br><br>“我也曾'+({cheyu:'以为声音大就一定能被理解',gubo:'想替所有人做好决定',qinlan:'害怕节目里的沉默',zhino:'坚持把一切修回原样',lin:'以保护的名义把门关上',fisher:'让伙伴一次又一次撑住',aran:'以为尊重就是完全不干预'}[e.character])+'。现在，我想学会先问一句。”',undefined,c.sprite)}},{text:'下次再见',fn:closeModal}],c.sprite);
 }else if(e.id==='echo-observe'){
  const i=state.area,[name,text]=OBSERVATIONS[i],recorded=state.echo.observed.includes(i);
  dialog(name,text,recorded?undefined:[{text:'和伙伴一起记录',fn:()=>{if(!state.echo.observed.includes(i)){state.echo.observed.push(i);state.team[0].bond=Math.min(100,state.team[0].bond+3);echoRecord(name+' · 羁绊 +3')}dialog(name,'线索已记入手记。回访时，留意身边的人怎样回应它。',undefined,state.team[0].id+'-front')}}],state.team[0].id+'-front');
 }else if(e.id==='echo-case')echoCases();
 else if(e.id==='echo-behavior'||e.id==='echo-behavior-extra'){
  const b=BEHAVIORS.find(b=>b[0]===e.behavior);if(!b){dialog('一起歇一会儿','你没有发出指令。伙伴自己挑了一块干燥的地面坐下。',undefined,state.team[0].id+'-front');return true;}
  const n=state.echo.period==='night'?1:0,key=b[0]+':'+n;const invite=state.echo.behaviors.includes(b[0]+':0')&&state.echo.behaviors.includes(b[0]+':1')&&!state.caught.includes(b[0])?[{text:'邀请它自愿同行',fn:()=>{if(state.caught.includes(b[0])){closeModal();return}const where=catchMon(b[0],10);echoRecord(b[1]+'选择与你同行');dialog(b[1],'它认出了白天和夜里陪它观察的人，轻轻碰了一下精灵球。'+where+'。',undefined,b[0]+'-front')}}]:[];
  dialog(b[1]+' · 自然观察',b[3+n]+'。<br>白天与夜间，它会有不同的行为。',[{text:state.echo.behaviors.includes(key)?'已经记下这次观察':'记下它自己的选择',fn:()=>{if(!state.echo.behaviors.includes(key)){state.echo.behaviors.push(key);seen(b[0]);state.berries+=1;echoRecord(b[1]+'：'+b[3+n]+' · 树果 +1')}closeModal()}},...invite,{text:'暂时离开',fn:closeModal}],b[0]+'-front');
 }else if(e.id==='echo-reply-result')dialog('沿途回信',e.line);
 return true;
}
function echoHub(){
 const e=state.echo,i=state.area,done=k=>e.milestones.includes(k),need=(stage,text)=>{if(state.stage<stage){dialog('还没到约好的时候',text);return true}return false};
 if(i===0){
  if(!e.choices.motivation){dialog('风铃响了三声','澈羽把空白明信片递给你：“等你回来，再看看出发时的答案吧。你为什么想出发？”',[['strong','想和伙伴一起变强'],['help','想帮到需要帮助的人'],['travel','想看看岛屿之外'],['hear','想听懂那声回响']].map(([key,text])=>({text,fn:()=>{e.choices.motivation=key;echoRecord('出发时的愿望：'+text);dialog('寄给未来的你','明信片收进了旧信箱。答案没有对错，沿途的行动会继续补写它。',undefined,'echo-apprentice')}})),'echo-apprentice');return;}
  dialog('风铃修理庭','旧信箱保存着你的出发记录。各地的事务台会继续收集地方的回答；调查旁边的委托牌，可以核对七年前的旧证据。',[{text:'查看委托与证据',fn:echoCases},{text:'坐到另一个时段',fn:echoRest},{text:'继续旅程',fn:closeModal}],'echo-apprentice');return;
 }
 if(i===1){if(need(2,'先去听听森林守望者的求助。大岩蛇守护的东西，就在树根后面。'))return;
  if(!done('shelter')){if(!e.observed.includes(1)){dialog('林音','先看看铃绳与棚柱。动手之前，我们得知道大岩蛇为什么不肯离开。',undefined,'npc-cooltrainer_f');return;}
   dialog('树根下的灯','棚柱已经裂开，大岩蛇一直替避雨棚承重。名单上“失联”的名字旁，后来又出现了手写的报平安。',[{text:'先支好棚柱，再解开铃绳',fn:()=>{e.choices.forest='calm';echoComplete('shelter','你们固定了棚柱，解开反复报警的铃绳。六尾走到棚下，大岩蛇终于松开了身体。门没有上锁，需要的人都可以来。')}},{text:'再检查一下',fn:closeModal}],'vulpix-front');return;}
 }else if(i===2){if(need(3,'先和老渔人在海边钓鱼，找回潮水带来的线索。'))return;
  if(!done('relay')){if(!done('shelter')){dialog('老渔人','先去森林确认避雨棚能安全使用。我们需要一个真正能接收获救者的地方。',undefined,'npc-fisher');return;}
   const roles=[['boat','航路引导'],['power','浮标供电'],['rescue','岸上接应']],names={fisher:'老渔人',cheyu:'澈羽',may:'小遥'};
   modal('雾里的接力',`<p>老渔人熟悉暗礁；澈羽会修接收器；小遥正在岸上照顾避难者。把任务交给合适的人，让拉普拉斯也有休息的机会。</p>${roles.map(([k,t])=>`<p><label>${t} <select id="job-${k}"><option value="">尚未安排</option>${Object.entries(names).map(([id,n])=>`<option value="${id}" ${e.jobs[k]===id?'selected':''}>${n}</option>`).join('')}</select></label></p>`).join('')}<button class="button" id="relay-confirm">确认接力安排</button>`);
   for(const [k]of roles)$('#job-'+k).onchange=ev=>{if(ev.target.value)e.jobs[k]=ev.target.value;else delete e.jobs[k];save()};
   $('#relay-confirm').onclick=()=>{if(e.jobs.boat!=='fisher'||e.jobs.power!=='cheyu'||e.jobs.rescue!=='may'){toast('根据每个人的专长分工：识路、供电、岸上接应各需要一位负责人。');return}echoComplete('relay','浮标依次亮起。潮生载着最后一位乘客靠岸，这次终于有人说：已经收到，你可以休息了。')};return;
  }
 }else if(i===3){if(need(4,'先与保育员了解这片湿地，再来讨论迁徙路线。'))return;
  if(!done('migration')){dialog('阿岚','施工围栏挡住了季节迁徙。修路的人也需要通往医院的近路。你建议怎样安排？',[['seasonal','分季节开放','你们留下季节通行牌。迁徙季让出湿地，其他时段开放维修通道。'],['detour','绕湿地建木廊','木廊绕过幼小的脚印，居民和迁徙的伙伴各有自己的通路。'],['delay','先暂停施工','施工暂缓，物资改从港口接力。湿地保留了安静，居民也约好了复评日期。']].map(([key,text,line])=>({text,fn:()=>{e.choices.migration=key;echoComplete('migration',line)}})),'npc-cooltrainer_m');return;}
 }else if(i===4){if(need(5,'先和伙伴完成星灯街的节奏挑战，再来听广播台的新节目。'))return;
  if(!done('overdrive')){dialog('琴岚','每个人都听见了广播，却没人知道谁在回答。电龙躲到音箱后，澈羽还想继续调高功率。旧铃谱中，三次呼唤之后原本有一格空白。',[{text:'把空白的一拍还给对岸',fn:()=>{modal('等待对岸的回答','<p id="quiet-beat">你放下扩音器。现在不必按键，给伙伴一点时间。</p>');const timer=setTimeout(()=>{e.choices.overdrive='silence';echoComplete('overdrive','你们关掉自动重播。沉默之后，港口传来一句“已经收到”。澈羽第一次没有立即接话，电龙从音箱后走了出来。')},3600);modalCleanup=()=>clearTimeout(timer)}},{text:'稍后再试',fn:closeModal}],'echo-host');return;}
 }else if(i===5){
  if(!done('council')){if(e.evidence.length<4){dialog('四响回廊','决定新协议之前，需要核对青岚镇、森林、港口、保育区四地的旧证据。各街区的委托牌保留着原始记录。');return;}
   if(!['shelter','relay','migration','overdrive'].every(done)){dialog('顾泊','纸上的证据需要各地的实际回答。请先完成避雨棚、港口接力、迁徙路线和广播台的事务。',undefined,'echo-engineer');return;}
   dialog('旧驿站的议席','证据一致：七年前许多救援已经成功，中心却没有签收地方的回答。现在，该如何公开这段记录？',[['public','公开完整调度记录'],['families','先让当事家庭确认'],['verify','先核实隐私再公开']].map(([key,text])=>({text,fn:()=>{e.choices.disclosure=key;echoComplete('council','你们约定：'+text+'。所有协议都必须保留拒绝和退出的权利。')}})),'echo-engineer');return;
  }
  if(!done('gubo')){dialog('顾泊','波士可多拉还撑着旧装置。“如果我让它停下，谁来保证大家安全？”旁边的机械支架已经就位，只等他松开最后的锁扣。',[{text:'确认支架承重，请伙伴退下来',fn:()=>{e.choices.gubo='release';echoComplete('gubo','锁扣松开后，桥没有倒下。波士可多拉靠在顾泊身旁。顾泊说：“原来我该修好的，是让它也能停下来的办法。”')}},{text:'继续查看回廊',fn:closeModal}],'aggron-front');return;}
  if(state.stage<6){dialog('顾泊','地方的回答已经整理完毕。去遗迹中央回应守护者，回来时我们一起签下新的协议。',undefined,'echo-engineer');return;}
  if(!done('final')){e.ending=endingFor(e);e.choices.final='rest';echoComplete('final',ENDINGS[e.ending].name+'：'+ENDINGS[e.ending].text+'<br><br>森屿回响，从此既有呼唤，也有被好好听见的回答。');return;}
  dialog(ENDINGS[e.ending]?.name||'回响之后',ENDINGS[e.ending]?.text||'旧旅程被保留下来。各地的人正在继续写自己的回答。',[{text:'翻看沿途记录',fn:echoJournal},{text:'继续走走',fn:closeModal}]);return;
 }
 dialog('地方的回答',e.log.filter(x=>!x.includes('观察')).at(-1)||'这里的事务已经完成，伙伴们可以歇一会儿了。',[{text:'查看委托与证据',fn:echoCases},{text:'坐到另一个时段',fn:echoRest},{text:'继续探索',fn:closeModal}]);
}
function echoRest(){state.echo.period=state.echo.period==='night'?'day':'night';echoRecord('在街区休息至'+(state.echo.period==='night'?'夜间':'白天'));echoRefresh();closeModal();toast('现在是'+(state.echo.period==='night'?'夜间':'白天')+'，看看居民和宝可梦有什么变化。');}
function echoCases(){
 const e=state.echo,i=state.area,buttons=[],lines=[];
 if(i<4){const [name,text]=EVIDENCE[i];if(state.stage>=5){lines.push('<b>'+name+'</b><br>'+text);buttons.push({text:e.evidence.includes(i)?'旧证据已核对':'核对并保存原始证据',fn:()=>{if(!e.evidence.includes(i)){e.evidence.push(i);echoRecord('旧证据：'+name)}echoCases()}})}else lines.push('等三枚碎片共鸣后，再来核对七年前的原始记录。');}
 for(const c of CASES.filter(c=>c.area===i&&(!c.post||state.stage===6))){const n=e.cases[c.id]||0;lines.push('<b>'+c.name+'</b><br>'+(n===3?c.after:c.steps[n]));if(n<3)buttons.push({text:'跟进委托 · '+c.name,fn:()=>{const n=e.cases[c.id]||0;if(n>=3){echoCases();return}e.cases[c.id]=n+1;echoRecord(c.name+'：'+c.steps[n]);if(n===2){state.berries+=3;echoRecord(c.after+' · 树果 +3');echoRefresh()}echoCases()}});}
 buttons.push({text:'休息，切换日夜',fn:echoRest},{text:'继续探索',fn:closeModal});dialog('街区委托与旧证据',lines.join('<br><br>')||'这里没有新的委托。看看身边的伙伴，或者回事务台聊聊。',buttons);
}
function echoJournal(){
 const e=state.echo,next=echoObjective(state),names=['青岚镇','微光森林','潮汐渔港','翠野保育区','星灯街','回响遗迹'];
 modal('森屿回响 · 地方手记',`<p>主线之外，六个故事街区会保留你作出的回答。打开「建筑 / 设施」，寻找「剧情街区」。旧存档可直接继续探索。</p>${next?'<p><b>下一步 · '+names[next.area]+'</b><br>'+next.goal+'</p><button class="button" id="echo-track">追踪街区下一步</button>':'<p>当前可办的街区事务已完成，继续主线或沿途探索。</p>'}<p>观察 ${e.observed.length}/6 · 旧证据 ${e.evidence.length}/4 · 自然行为 ${e.behaviors.length}/12</p><p>已完成事务：${e.milestones.map(k=>({shelter:'树根下的灯',relay:'雾里的接力',migration:'围栏之外',overdrive:'空白的一拍',council:'旧驿站议席',gubo:'承重',final:'新的协议'}[k])).join('、')||'等待你留下第一个回答'}</p><p>已核对地区：${e.evidence.map(i=>names[i]).join('、')||'三枚碎片共鸣后开始回访'}</p>${e.ending?'<h3>'+ENDINGS[e.ending].name+'</h3><p>'+ENDINGS[e.ending].text+'</p>':''}<button class="button" id="old-journal">主线、神兽与道路手记</button><h3>最近的回答</h3>${e.log.slice(-16).reverse().map(t=>'<p>'+escapeHTML(t)+'</p>').join('')}`);
 $('#old-journal').onclick=legacyJournal;
 if(next)$('#echo-track').onclick=()=>{closeModal();if(state.area===next.area&&world.interior?.service==='echo-district'){world.goTo(next.target);return}travel(next.area);world.goTo('echo-district');toast('走近街区入口后按 E。'+next.goal)};
}
boot();
const buildingsButton=document.createElement('button');buildingsButton.id='buildings';buildingsButton.textContent='⌂ 建筑 / 设施';buildingsButton.onclick=buildings;document.querySelector('.world-top').appendChild(buildingsButton);


function observeRoute(e){
 const r=ROUTES[e.route],key=e.route+':'+e.point;
 const recorded=state.surveys.includes(key);
 dialog(r.notes[e.point],r.lines[e.point]+'<br><br><b>'+RELAY_CHAPTERS[e.route][0]+'</b><br>'+RELAY_CHAPTERS[e.route][1]+(recorded?'<br><br>这条发现已经记在手记里。':'<br><br>和伙伴一起把这条发现记下来。'),recorded?undefined:[{text:'记录这次发现',fn:()=>{
  if(state.surveys.includes(key)){closeModal();return}
  state.surveys.push(key);state.team[0].bond=Math.min(100,state.team[0].bond+2);
  const count=state.surveys.filter(k=>k.startsWith(e.route+':')).length;
  let reward='伙伴羁绊 +2。';
  if(count===3){state.balls+=3;state.berries+=3;state.money+=180;reward+=' 完成本条路线观察：精灵球 ×3、树果 ×3、旅费 ₽180。'}
  save();sync();dialog('旅行手记 · '+r.name,`已记录 ${count}/3。${reward}`,undefined,r.npc);
 }},{text:'先继续探索',fn:closeModal}],r.npc);
}

function relayReport(){
 if(state.relayReported){dialog('大木博士 · 新的路图','六封回信已经收好。我们会在每个岔路口挂上新的路牌，让下一位旅人知道，他的声音总有人听见。');return}
 dialog('最后一封回信，寄给明天','博士把六条路的记录铺开：风铃送出消息，草原护送生命，山路传递灯光，古道留下求救，海岸接人回家，山庭迎接明天。<br><br>“核心修好了，只是让声音能传过去。你们走完这些路，才让声音有了愿意回答的人。”',[{text:'把路图留给下一位旅人',fn:()=>{if(!state.relayReported){state.relayReported=true;state.coins+=60;save();sync()}dialog('森屿回响 · 路的另一端','博士把你的记录放在研究所门口。奖励：60 枚代币。故事没有被锁进遗迹，它留在每一条还有人经过的路上。')}}]);
}

