import {CanvasTexture,MeshBasicMaterial,SRGBColorSpace,RepeatWrapping} from './vendor/three.module.js';
const crops={celadon_gym_floor_mat:[.29,.29,.42,.42],grass_ground_tile:[.17,.17,.66,.66],route1_dirt_path_straight_tile:[.07,.36,.86,.30],pale_pavement_tile:[.15,.15,.70,.70],cave_floor_tile:[.15,.15,.70,.70],celadon_game_corner_floor_tile:[.19,.19,.62,.62],celadon_department_store_floor_tile:[.21,.21,.58,.58],viridian_gym_floor_tile:[.09,.09,.82,.82]};
const tiles=new Map();
export async function prepareSurfaces(){await Promise.all(Object.entries(crops).map(async([name,crop])=>{const im=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('Surface missing: '+name));i.src='assets/surface-'+name+'.png'});const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');g.imageSmoothingEnabled=false;const [x,y,w,h]=crop;
 // Mirrored quadrants meet continuously; source backdrop and outer borders are excluded.
 for(let a=0;a<2;a++)for(let b=0;b<2;b++){g.save();g.translate(a?256:0,b?256:0);g.scale(a?-1:1,b?-1:1);g.drawImage(im,x*im.width,y*im.height,w*im.width,h*im.height,0,0,128,128);g.restore()}tiles.set(name,c);
}));}
export function sceneSurface(w){const s=w.interior?.service;if(s?.startsWith('wildland-'))return ['grass_ground_tile','cave_floor_tile','route1_dirt_path_straight_tile'][Number(s.slice(-1))];if(s==='arcade')return'celadon_game_corner_floor_tile';if(s==='shop')return'celadon_department_store_floor_tile';if(s==='ranger'||s==='pet')return'celadon_gym_floor_mat';if(s==='lab')return'viridian_gym_floor_tile';if(s==='grotto')return'grass_ground_tile';if(s==='cave')return'cave_floor_tile';if(s&&!s.startsWith('route-')&&s!=='echo-district')return'pale_pavement_tile';return ['route1_dirt_path_straight_tile','grass_ground_tile','route1_dirt_path_straight_tile','grass_ground_tile','pale_pavement_tile','cave_floor_tile'][w.area];}
export function roadPattern(g,w){const name=sceneSurface(w),tile=tiles.get(name);if(!tile)return null;w.roadSurface=name;return g.createPattern(tile,'repeat');}
export function roomSurface(w,width=19,depth=17){const name=sceneSurface(w),tile=tiles.get(name);if(!tile)return;const texture=new CanvasTexture(tile);texture.colorSpace=SRGBColorSpace;texture.wrapS=texture.wrapT=RepeatWrapping;texture.repeat.set(width/10,depth/10);const m=w.floor(0,0,width,depth,0xffffff,.021);m.material.dispose();m.material=new MeshBasicMaterial({map:texture,toneMapped:false});m.userData.surface=name;w.roadSurface=name;}
