const { chromium }=require('C:/Users/Sheng/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const page=await browser.newPage({viewport:{width:1440,height:1060}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const diag=()=>page.evaluate(()=>echoDiagnostics());
async function saveState(){await page.locator('#save').click();return page.evaluate(()=>JSON.parse(localStorage.getItem('pokemon-echoes-v1')))}
async function go(area){await page.locator('[data-panel="map"]').first().click();await page.locator(`[data-travel="${area}"]`).click()}
async function track(){await page.locator('#track').click();await page.waitForFunction(()=>{const d=echoDiagnostics();const q=['prof','warden','fish','ranger','arcade','guardian','prof'][d.stage];const t=d.entities.find(e=>e.id===q);return t&&Math.hypot(t.x-d.position.x,t.z-d.position.z)<2.8},{},{timeout:20000});await page.waitForTimeout(600);await page.keyboard.press('e')}
async function fight(){for(let i=0;i<35;i++){if(!(await diag()).battle)return;const b=page.locator('[data-battle="attack"]');await b.waitFor();await b.waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('[data-battle="attack"]')?.disabled);await b.click();await page.waitForTimeout(1600)}throw Error('battle exceeded 35 turns')}
async function timing(count){for(let i=0;i<15;i++){if(!await page.locator('#timing-hit').count())return;await page.waitForFunction(()=>{const c=document.querySelector('.timing-cursor');return c&&parseFloat(c.style.left)>46&&parseFloat(c.style.left)<52},{},{polling:'raf'});await page.keyboard.press('Space');await page.waitForTimeout(180)}}
await page.goto('http://127.0.0.1:4188');await page.waitForFunction(()=>window.echoDiagnostics?.().ready);await page.waitForTimeout(500);assert.equal((await diag()).stage,0);await track();await page.getByRole('button',{name:'选择一位新的同行伙伴'}).click();await page.locator('[data-starter="bulbasaur"]').click();assert.equal((await diag()).stage,1);console.log('PASS starter and first quest');
await page.locator('[data-panel="team"] ').first().click();await page.locator('[data-lead="1"]').click();await page.locator('#close').click();assert.equal((await diag()).team[0].id,'bulbasaur');
await go(1);await track();await page.getByRole('button',{name:'帮助森林，开始对战'}).click();await fight();assert.equal((await diag()).stage,2);await page.getByRole('button',{name:'前往潮汐渔港'}).click();console.log('PASS forest quest, elemental battle and shared XP');
await track();await timing(1);await page.getByRole('button',{name:'回到岸边'}).click();assert.equal((await diag()).stage,3);console.log('PASS fishing and second fragment');
await go(3);
// Follow the moving Scyther through the same accessible directory used by players.
// Use the accessible field directory so a moving creature remains the navigation target.
 await page.locator('#buildings').click();await page.getByRole('button',{name:/飞天螳螂/}).click();await page.waitForFunction(()=>{const d=echoDiagnostics(),e=d.entities.find(e=>e.id==='wild'&&e.pokemon==='scyther');return e&&Math.hypot(e.x-d.position.x,e.z-d.position.z)<2.2});await page.keyboard.press('e');await page.locator('#bait').waitFor();for(let i=0;i<3;i++)await page.locator('#bait').click();await page.locator('#safari-ball').click();await page.getByRole('button',{name:'谢谢你，我的新朋友'}).click();assert.equal((await diag()).stage,4);console.log('PASS safari bait, capture and third fragment');
await go(4);await page.locator('#pet-shortcut').click();await page.locator('#rhythm').click();await timing(3);await page.getByRole('button',{name:'太棒了，继续冒险'}).click();assert.equal((await diag()).stage,5);console.log('PASS companion rhythm and ruin unlock');
await go(5);await track();await page.getByRole('button',{name:'一起回应这份心跳'}).click();await fight();assert.equal((await diag()).stage,6);await page.getByRole('button',{name:'继续我们的旅程'}).click();assert.ok((await diag()).team.some(m=>m.id==='mew'));console.log('PASS final battle and playable ending');
let state=await saveState();await page.reload();await page.waitForFunction(()=>window.echoDiagnostics?.().ready);assert.equal((await diag()).stage,6);assert.equal((await diag()).area,5);assert.equal((await diag()).team.length,state.team.length);console.log('PASS save/reload');
await go(0);await page.screenshot({path:path.join(__dirname,'../desktop-played.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(__dirname,'../mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await page.locator('[data-panel="map"]').click();assert.equal(await page.locator('[data-travel]').count(),6);await page.locator('#close').click();console.log('PASS mobile layout and map');
assert.deepEqual(errors,[]);console.log('PASS no browser errors');console.log(JSON.stringify({stage:state.stage,team:state.team.map(m=>m.id),fished:state.fished,safari:state.safari,petWins:state.petWins,errors}));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});

